= Model structure

== Structure overview

[plantuml]
----
legend
[[../geometry/object-classes.html#_environment_t Environment_Root (T)]]
|_[[../geometry/object-classes.html#_grp_terrain Grp_Terrain]]
|_[[../geometry/object-classes.html#_grp_environment_objects Grp_Environment_Objects]]
  |_ [[../geometry/object-classes.html#_grp_buildings Grp_Buildings]]
  |_ [[../geometry/object-classes.html#_grp_vegetation Grp_Vegetation]]
|_[[../geometry/object-classes.html#_grp_road_network Grp_Road_Network]]
  |_ [[../geometry/object-classes.html#_grp_drivable_area Grp_Drivable_Area]]
  |_ [[../geometry/object-classes.html#_grp_sidewalks Grp_Sidewalks]]
  |_ [[../geometry/object-classes.html#_grp_road_marks Grp_Road_Marks]]
  |_ [[../geometry/object-classes.html#_grp_road_object Grp_Road_Objects]]
  |_ [[../geometry/object-classes.html#_grp_signals Grp_Signals]]
    |_ [[../geometry/object-classes.html#_grp_sign_idx_t Grp_Sign_<signal_idx> (T)]]
    |_ [[../geometry/object-classes.html#_traffic_light_idx_t Grp_Traffic_Light_<signal_idx> (T)]]
end legend
----

////
[plantuml]
----
legend
Root (T)
|-- Grp_Terrain
|-- Grp_Objects
----|--Grp_Buildings
----|--Grp_Vegetation
|-- Grp_Road_Network
----|--Grp_Driving_Area
----|--Grp_Sidewalks
----|--Grp_Road_Marks
----|--Grp_Road_Objects
----|--Grp_Signals
-------|--Grp_Sign_<signal_idx> (T)
-------|--Grp_Traffic_Light_<signal_idx> (T)

end legend
----
////

== Environment_Root (T)

The environment contains terrain, buildings, objects and traffic areas, e.g., roads, including all stationary traffic items, such as traffic signals, signs or lights. 

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===



== Grp_Terrain

The terrain is characterized by the environment's ground structure, such as hills, mountains, or flat territory, thus, the landscape in general. It does not include local elevations like vegetation, buildings or other human-made structures.

////
.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===
////

Add a figure.

//.<Figure caption>


== Grp_Environment_Objects

Environment Objects include buildings, vegetation and any other (stationary) objects of the surrounding that are elevations or other changes to the terrain. 

////
.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===
////

Add a figure.

.<Figure caption>

== Grp_Buildings

Buildings belong to the human-made environment, including , e.g., houses, towers, or skysrapers.

////
.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===
////

Add a figure.

.<Figure caption>

== Grp_Vegetation

Vegetation includes all organic growths or plants that are part of the landscape and grow on the terrain or on human-made structures, e.g., between roads and buildings. 

////
.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===
////

Add a figure.

.<Figure caption>


== Grp_Road_Network

The Road Network includes the drivable area, sidewalks, and any other traffic objects such as traffic signals, signs, traffic lights or other traffic objects.

////
.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===
////

Add a figure.

.<Figure caption>
//image::images/Vehicle_Structure_Door_Coord_Frame.svg[width=70%, scalewidth=10cm]

== Grp_Drivable_Area

The drivable area includes any surfaces that are part of the road structure including lanes and parking areas. It is comparable to the scope of the OpenDrive standard for on-road use cases.

////
.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===
////

Add a figure.

.<Figure caption>
//image::images/Vehicle_Structure_Door_Coord_Frame.svg[width=70%, scalewidth=10cm]

== Grp_Sidewalks 

Sidewalks are traffic spaces that are dedicated for pedestrians and sometimes cyclists. 

////
.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===
////

Add a figure.

.<Figure caption>




== Grp_Road_Marks


Road marks include any markings on the road and traffic spaces.

////
.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===
////

Add a figure.

.<Figure caption>
//image::images/Vehicle_Structure_Door_Coord_Frame.svg[width=70%, scalewidth=10cm]

== Grp_Road_Objects

Road Objects include all other objects on or nearby the road, excluding signals, i.e., signs and traffic lights.
////
.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===
////

Add a figure.

.<Figure caption>


== Grp_Signals


Traffic signals, including signs and lights. Signals describe the relevant area or volume of a traffic signal only. Posts and gantrys are considered road objects.

////
.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===

////
Add a figure.

.<Figure caption>



== Grp_Sign_<signal_idx> (T)


Traffic signs belong to traffic signals. Therefore, they are indexed using a signal-index and cannot have the same ID as a traffic light, which is also enumerated by the signal-index. The signal-index can be taken over from OpenDRIVE or OSI. If no predefined indices exist, they can be generated by iterating over all signals from (0,...,n).

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


Add a figure.

.<Figure caption>


== Grp_Traffic_Light_<signal_idx> (T)


Traffic lights belong to traffic signals to provide temporary changes in illumination. The signal-index can be taken over from OpenDRIVE or OSI. If no predefined indices exist, they can be generated by iterating over all signals from (0,...,n). The indices are used for both, traffic signs and traffic lights. A  traffic light cannot have the same index ID as a traffic sign in a single environment. 

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


Add a figure.

.<Figure caption>
//image::images/Vehicle_Structure_Door_Coord_Frame.svg[width=70%, scalewidth=10cm]


