= Model structure

== Structure overview

[plantuml]
----
legend
[[../geometry/object-classes.html#_environment_t Environment_Root]]
|_[[../geometry/object-classes.html#_grp_terrain Grp_Terrain]]
|_[[../geometry/object-classes.html#_grp_environment_objects Grp_Environment_Objects]]
  |_ [[../geometry/object-classes.html#_grp_buildings Grp_Buildings]]
  |_ [[../geometry/object-classes.html#_grp_vegetation Grp_Vegetation]]
|_[[../geometry/object-classes.html#_grp_road_network Grp_Road_Network]]
  |_ [[../geometry/object-classes.html#_grp_drivable_area Grp_Drivable_Area]]
  |_ [[../geometry/object-classes.html#_grp_sidewalks Grp_Sidewalks]]
  |_ [[../geometry/object-classes.html#_grp_road_marks Grp_Road_Marks]]
  |_ [[../geometry/object-classes.html#_grp_road_object Grp_Road_Objects]]
  |_ [[../geometry/object-classes.html#_grp_signals Grp_Signals]]
    |_ [[../geometry/object-classes.html#_grp_sign_idx_t Grp_Sign_<signal_idx>]]
    |_ [[../geometry/object-classes.html#_traffic_light_idx_t Grp_Traffic_Light_<signal_idx>]]
end legend
----

== Environment_Root

The environment consists of the terrain, buildings, objects, and traffic areas, for example roads. It also includes all stationary traffic items, such as traffic signals, signs or lights. 

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


== Grp_Terrain

The terrain is characterized by the environment's ground structure, such as hills, mountains, or flat territory, meaning, the landscape in general. It does not include local elevations like vegetation, buildings, or other human-made structures.

NOTE: Add a figure.

== Grp_Environment_Objects

An environment object consists of buildings, vegetation, and any other (stationary) object of the surrounding. An environment object causes a local elevation or other additions in the terrain. 

NOTE: Add a figure.

== Grp_Buildings

A building is a human-made structure and includes houses, towers, or skyscrapers.

NOTE: Add a figure.

== Grp_Vegetation

The vegetation includes all organic growths or plants that are part of the landscape. Vegetation can grow on the terrain or on human-made structures, for example between roads and buildings. 

NOTE: Add a figure.

== Grp_Road_Network

The road network is the entirety of a road. It includes the drivable area, sidewalks, and any other traffic objects, such as traffic signals, signs, or traffic lights.

NOTE: Add a figure.

== Grp_Drivable_Area

The drivable area is a traffic space that is dedicated to vehicles. It is the surface part of the road structure on which vehicles drive and includes lanes and parking areas. The drivable area for ASAM OpenMATERIAL is comparable to the scope of the ASAM OpenDRIVE standard for on-road use cases.

NOTE: Add a figure.

== Grp_Sidewalks 

A sidewalk is a traffic space that is dedicated to pedestrians and sometimes cyclists. They are usually adjacent to the drivable area.

NOTE: Add a figure.

== Grp_Road_Marks

A road mark includes any markings on the road and traffic spaces.

NOTE: Add a figure.

== Grp_Road_Objects

A road object includes all other objects on or nearby the road, excluding signals.

NOTE: Add a figure.

== Grp_Signals

A signal in traffic is a visual sign used to control the flow of traffic. A traffic signal can be both a sign and a light. Signals describe the relevant area or volume of a traffic signal only. Posts and gantries are considered road objects.

NOTE: Add a figure.

== Grp_Sign_<signal_idx>

Traffic signs belong to traffic signals. They are indexed using a <signal_index>. The <signal_index> can be taken over from ASAM OpenDRIVE or ASAM OSI. If no predefined indices exist, they can be generated by iterating over all signals from (0,...,n). The indices are used for both traffic signs and traffic lights. A traffic sign cannot have the same index as a traffic light in a single environment.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


NOTE: Add a figure.

== Grp_Traffic_Light_<signal_idx>

Traffic lights belong to traffic signals. They show temporary changes in illumination. The <signal_index> can be taken over from ASAM OpenDRIVE or ASAM OSI. If no predefined indices exist, they can be generated by iterating over all signals from (0,...,n). The indices are used for both traffic signs and traffic lights. A traffic light cannot have the same index as a traffic sign in a single environment. 

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===

NOTE: Add a figure.
