= Model structure

== Structure overview

[plantuml]
----
legend
[[../geometry/object-classes.html#_environment_t Environment_Root (T)]]
|_[[../geometry/object-classes.html#_terrain_t Terrain]]
|_[[../geometry/object-classes.html#_objects_t Objects]]
  |_ [[../geometry/object-classes.html#_buildings Buildings]]
  |_ [[../geometry/object-classes.html#_vegetation Vegetation]]
|_[[../geometry/object-classes.html#_road_network_t Road_Network]]
  |_ [[../geometry/object-classes.html#_drivable_area_t Drivable_Area]]
  |_ [[../geometry/object-classes.html#_sidewalk_t Sidewalk]]
  |_ [[../geometry/object-classes.html#_road_marks_t Road_Marks]]
  |_ [[../geometry/object-classes.html#_road_object_idx_t Road_Object_<object_idx> (T)]]
  |_ [[../geometry/object-classes.html#_signal_signal_idx_t Signal_<signal_idx> (T)]]
    |_ [[../geometry/object-classes.html#_sign_idx_t Sign_<sign_idx> (T)]]
    |_ [[../geometry/object-classes.html#_traffic_light_idx_t Traffic_Light_<traffic_light_idx> (T)]]
    |_ [[../geometry/object-classes.html#_cover_idx_t Cover<cover_idx> (T)]]
end legend
----

////
[plantuml]
----
legend
Root (T)
|-- Terrain
|-- Objects
----|--Buildings
----|--Vegetation
|-- Road_Network
----|--Driving_Area
----|--Sidewalks
----|--Road_Marks
----|--Road_Object_<object_idx> (T)
----|--Signal_<signal_idx> (T)
-------|--Sign_<sign_idx> (T)
-------|--Bulb_<bulb_idx> (T)


end legend
----
////

== Environment_Root (T)

The environment contains terrain, buildings, objects and traffic areas, e.g., roads, including all stationary traffic items, such as traffic signals, signs or lights. 

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===



== Terrain

The terrain is characterized by the environment's ground structure, such as hills, mountains, or flat territory, thus, the landscape in general. It does not include local elevations like vegetation, buildings or other human-made structures.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


Add a figure.

//.<Figure caption>


== Objects

Objects include buildings, vegetation and any other (stationary) objects of the surrounding that are elevations or other changes to the terrain. 

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


Add a figure.

.<Figure caption>

== Buildings

Buildings belong to the human-made environment, including , e.g., houses, towers, or skysrapers.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


Add a figure.

.<Figure caption>

== Vegetation

Vegetation includes all organic growths or plants that are part of the landscape and grow on the terrain or on human-made structures, e.g., between roads and buildings. 

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


Add a figure.

.<Figure caption>


== Road_Network

The Road Network includes the drivable area, sidewalks, and any other traffic objects such as traffic signals, signs, traffic lights or other traffic objects.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


Add a figure.

.<Figure caption>
//image::images/Vehicle_Structure_Door_Coord_Frame.svg[width=70%, scalewidth=10cm]

== Drivable_Area

The drivable area includes any surfaces that are part of the road structure including lanes and parking areas. It is comparable to the scope of the OpenDrive standard for on-road use cases.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


Add a figure.

.<Figure caption>
//image::images/Vehicle_Structure_Door_Coord_Frame.svg[width=70%, scalewidth=10cm]

== Sidewalks 

Sidewalks are traffic spaces that are dedicated for pedestrians and sometimes cyclists. 

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


Add a figure.

.<Figure caption>




== Road_Marks


Road marks include any markings on the road and traffic spaces.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


Add a figure.

.<Figure caption>
//image::images/Vehicle_Structure_Door_Coord_Frame.svg[width=70%, scalewidth=10cm]

== Road_Object_<object_idx> (T)


Road Objects include all other objects on or nearby the road, excluding signals, signs, and traffic lights.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


Add a figure.

.<Figure caption>


== Signal_<signal_idx> (T)


Traffic signals.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


Add a figure.

.<Figure caption>



== Sign_<sign_idx> (T)


Traffic signs.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


Add a figure.

.<Figure caption>


== Traffic_Light_<traffic_light_idx> (T)


Traffic lights belong to traffic signals to provide temporary changes in illumination. 

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


Add a figure.

.<Figure caption>
//image::images/Vehicle_Structure_Door_Coord_Frame.svg[width=70%, scalewidth=10cm]


== Cover_<cover_idx> (T)

A cover is a temporary or longterm enveloping or concealment over a traffic signal.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


Add a figure.

.<Figure caption>
