= Model structure

:home-path: ../..
:imagesdir: {home-path}/_images
:includedir: {home-path}/_images

== Table of content

[plantuml]
----
legend
Root
|_ Grp_Vehicle_Part_<part_idx>_<keyword>
  |_ Grp_Exterior_<part_idx>
    |_ Grp_Exterior_Static_<part_idx>
    |_ Grp_Exterior_Dynamic_<part_idx>
      |_ Grp_Wheel_<part_idx>_<axle_idx>_<wheel_idx>
        |_ Grp_Wheel_Steering_<part_idx>_<axle_idx>_<wheel_idx>
        |_ Grp_Wheel_Steering_Rotating_<part_idx>_<axle_idx>_<wheel_idx>
      |_ Grp_Door_Front_<part_idx>_<door_front_idx>
      |_ Grp_Door_Left_<part_idx>_<door_left_idx>
      |_ Grp_Door_Right_<part_idx>_<door_right_idx>
      |_ Grp_Door_Rear_<part_idx>_<door_rear_idx>
      |_ Grp_Door_Top_<part_idx>_<door_top_idx>
      |_ Grp_Door_Bottom_<part_idx>_<door_bottom_idx>
      |_ Grp_Light_Day_Left_<part_idx>_<day_left_idx>
      |_ Grp_Light_Day_Right_<part_idx>_<day_right_idx>
      |_ Grp_Light_Low_Beam_Left_<part_idx>_<low_beam_left_idx>
      |_ Grp_Light_Low_Beam_Right_<part_idx>_<low_beam_right_idx>
      |_ Grp_Light_High_Beam_Left_<part_idx>_<high_beam_left_idx>
      |_ Grp_Light_High_Beam_Right_<part_idx>_<high_beam_right_idx>
      |_ Grp_Light_Corner_Left_<part_idx>_<corner_left_idx>
      |_ Grp_Light_Corner_Right_<part_idx>_<corner_right_idx>
      |_ Grp_Light_Position_Left_<part_idx>_<position_left_idx>
      |_ Grp_Light_Position_Right_<part_idx>_<position_right_idx>
      |_ Grp_Light_Park_Left_<part_idx>_<park_left_idx>
      |_ Grp_Light_Park_Right_<part_idx>_<park_right_idx>
      |_ Grp_Light_Indicator_Left_<part_idx>_<indicator_left_idx>
      |_ Grp_Light_Indicator_Right_<part_idx>_<indicator_right_idx>
      |_ Grp_Light_License_Plate_<part_idx>_<license_plate_light_idx>
      |_ Grp_Light_Tail_Left_<part_idx>_<tail_left_idx>
      |_ Grp_Light_Tail_Right_<part_idx>_<tail_right_idx>
      |_ Grp_Light_Brake_Left_<part_idx>_<brake_left_idx>
      |_ Grp_Light_Brake_Center_<part_idx>_<brake_center_idx>
      |_ Grp_Light_Brake_Right_<part_idx>_<brake_right_idx>
      |_ Grp_Light_Reverse_Left_<part_idx>_<reverse_left_idx>
      |_ Grp_Light_Reverse_Right_<part_idx>_<reverse_right_idx>
      |_ Grp_Light_Fog_Left_<part_idx>_<fog_left_idx>
      |_ Grp_Light_Fog_Right_<part_idx>_<fog_right_idx>
      |_ Grp_Light_Warning_<part_idx>_<warning_idx>
      |_ Grp_Mirror_Side_Mounting_Left_<part_idx>_<side_mirror_mounting_left_idx>
      |_ Grp_Mirror_Side_View_Left_<part_idx>_<side_mirror_view_left_idx>
      |_ Grp_Mirror_Side_Mounting_Right_<part_idx>_<side_mirror_mounting_right_idx>
      |_ Grp_Mirror_Side_View_Right_<part_idx>_<side_mirror_view_right_idx>
      |_ Grp_Mirror_Blindspot_Mounting_<part_idx>_<blindspot_mirror_mounting_idx>
      |_ Grp_Mirror_Blindspot_View_<part_idx>_<blindspot_mirror_view_idx>
      |_ Grp_License_Plate_<part_idx>_<license_plate_idx>
      |_ Grp_Convertible_Top_<part_idx>
      |_ Grp_Sensor_<part_idx>_<sensor_idx>
  |_ Grp_Interior_<part_idx>
    |_ Grp_Interior_Static_<part_idx>
    |_ Grp_Interior_Dynamic_<part_idx>
      |_ Grp_Steering_Wheel_<part_idx>
      |_ Grp_Eyepoint_<part_idx>_<eyepoint_idx>
      |_ Grp_Mirror_Rearview_Mounting_<part_idx>_<rearview_mirror_mounting_idx>
      |_ Grp_Mirror_Rearview_View_<part_idx>_<rearview_mirror_view_idx>
      |_ Grp_Seat_<part_idx>_<seat_idx>
end legend
----

== Grp_Vehicle_Part_<part_idx>_<keyword> 

A vehicle part is a large structure of the vehicle (part), that moves independently from other parts of the same vehicle.
This mainly applies to articulated vehicles, e.g. a front loader with a hinged axis or an articulated bus with a hinge in the middle.
When a vehicle part can be detached, like a trailer, it is to be treated as a separate object and not a vehicle part.

Standard vehicles only have one part and no keyword.
Therefore, only one Grp_Vehicle_Part exists with the name `Grp_Vehicle_Part_0`.

The `<part_idx>` must be added to all sub-nodes, as multiple nodes with the same name in different vehicle parts are not possible.
There cannot be a node `Grp_Exterior` in both `Grp_Vehicle_Part_0` and `Grp_Vehicle_Part_1`.

NOTE: Define the origin of the vehicle (part)

NOTE: Add description and examples for keywords

NOTE: Add a figure visualizing e.g. a hinged bus to explain what vehicle parts are.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Exterior_<part_idx>

This group contains all elements of the exterior of the vehicle (part).

This group typically does not move in the simulation and therefore does not have its own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle (part)

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Exterior_Static_<part_idx>

This group contains all static elements of the exterior of the vehicle (part).
Static elements are geometry structures that have a fixed position and orientation relative to the origin on the vehicle (part) throughout a simulation.
They also do not change their state during the simulation, therefore lights are considered dynamic.

This group typically does not move in the simulation and therefore does not have its own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle (part)

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Exterior_Dynamic_<part_idx>

This group contains all dynamic elements of the exterior of the vehicle (part).
Dynamic elements are geometry structures which position and orientation relative to the origin on the vehicle (part) might change throughout a simulation.
They may also change their state during the simulation, therefore lights are considered dynamic.

This group typically does not move in the simulation and therefore does not have its own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle (part)

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Wheel_<part_idx>_<axle_idx>_<wheel_idx>

This group contains all geometries of one wheel assembly.
This may include tire, rim, brake caliper etc.

The `<axle_idx>` denotes the index of the axle the wheel is mounted to, counting from the front to the rear, starting with 0.
The `<wheel_idx>` denotes the index of the wheel on the specified axle, counting from right to left (in positive y direction), starting with 0.
Example: The wheel on the front left of a standard vehicle would be `Grp_Wheel_0_1`.

Steering of the wheel is implemented by a rotation around the z-axis.
Wheel camber is defined by a rotation around the x-axis.
Suspension deflection is represented by a translation along the z-axis.
Zero rotation and and translation around all axles are defined in neutral load conditions.
In the 3D model, both caster and camber angles are neglected.

image::Grp_Wheel.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the wheel

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Wheel_Steering_<part_idx>_<axle_idx>_<wheel_idx>

This group contains all components of the wheel assembly, that follow the steering motion but not the rotation of the wheel, e.g. brake calipers.

The indices are the same as in the parent group.

This group typically does not move independently in the simulation as it moves with the parent transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the wheel

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Wheel_Steering_Rotating_<part_idx>_<axle_idx>_<wheel_idx>

This group contains all components of the wheel assembly, that follow the steering motion as well as the rotation of the wheel, e.g. tire and rim.

The indices are the same as in the parent group.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the wheel

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing towards the door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Door_Front_<part_idx>_<door_front_idx>

The group contains all components of a door in the front of the vehicle (part).
This includes e.g. the engine cover.
This also includes the interior parts of the door, since they are moved as one unit.

The `<door_front_idx>` is the index for all doors in the front counting from right to left (in positive y direction), starting with 0.

image::Grp_Door_Front.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing towards the door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis
|===


== Grp_Door_Left_<part_idx>_<door_left_idx>

The group contains all components of a door on the left side of the vehicle (part).
This also includes the interior parts of the door, since they are moved as one unit.

The `<door_left_idx>` is the index for all doors on the left counting from front to rear, starting with 0.

image::Grp_Door_Left[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing towards the door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis
|===


== Grp_Door_Right_<part_idx>_<door_right_idx>

The group contains all components of a door on the right side of the vehicle (part).
This also includes the interior parts of the door, since they are moved as one unit.

The `<door_right_idx>` is the index for all doors on the right counting from front to rear, starting with 0.

image::Grp_Door_Right[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing towards the door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis
|===


== Grp_Door_Rear_<part_idx>_<door_rear_idx>

The group contains all components of a door in the rear of the vehicle (part).
This includes e.g. the trunklid.
This also includes the interior parts of the door, since they are moved as one unit.

The `<door_rear_idx>` is the index for all doors in the rear counting from right to left (in positive y direction), starting with 0.

image::Grp_Door_Rear.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing towards the door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis
|===


== Grp_Door_Top_<part_idx>_<door_top_idx>

The group contains all components of a door on the top of the vehicle (part).
This also includes the interior parts of the door, since they are moved as one unit.

The `<door_top_idx>` is the index for all doors on the top counting from front to rear, starting with 0.

image::Grp_Door_Top.svg[, 1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing towards the door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis
|===


== Grp_Door_Bottom_<part_idx>_<door_bottom_idx>

The group contains all components of a door on the bottom of the vehicle (part).
This also includes the interior parts of the door, since they are moved as one unit.

The `<door_bottom_idx>` is the index for all doors on the bottom counting from front to rear, starting with 0.

NOTE: Add a figure with a hatch on the bottom.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis
|===


== Grp_Light_Day_Left_<part_idx>_<day_left_idx>

This group contains all parts of a daytime running light on the left side of the vehicle (part).

The `<day_left_idx>` is the index for all daytime running lights on the left counting from right to left (in positive y direction), starting with 0.

//NOTE: Add a figure. This figure might ba applicable to all lights on the front left. I don't think we have to distinguish in the figures between the different kinds of lights.
image::Grp_Light_Day_Left.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Day_Right_<part_idx>_<day_right_idx>

This group contains all parts of a daytime running light on the right side of the vehicle (part).

The `<day_left_idx>` is the index for all daytime running lights on the right counting from right to left (in positive y direction), starting with 0.

//NOTE: Add a figure. This figure might be applicable to all lights on the front right. I don't think we have to distinguish in the figures between the different kinds of lights.
image::Grp_Light_Day_Right.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Low_Beam_Left_<part_idx>_<low_beam_left_idx>

This group contains all parts of a low beam light on the left side of the vehicle (part).

The `<low_beam_left_idx>` is the index for all low beam lights on the left counting from right to left (in positive y direction), starting with 0.

image::Grp_Light_Day_Left.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Low_Beam_Right_<part_idx>_<low_beam_right_idx>

This group contains all parts of a low beam light on the right side of the vehicle (part).

The `<low_beam_right_idx>` is the index for all low beam lights on the right counting from right to left (in positive y direction), starting with 0.

image::Grp_Light_Day_Right.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_High_Beam_Left_<part_idx>_<high_beam_left_idx>

This group contains all parts of a high beam light on the left side of the vehicle (part).

The `<high_beam_left_idx>` is the index for all high beam lights on the left counting from right to left (in positive y direction), starting with 0.

image::Grp_Light_Day_Left.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_High_Beam_Right_<part_idx>_<high_beam_right_idx>

This group contains all parts of a high beam light on the right side of the vehicle (part).

The `<high_beam_right_idx>` is the index for all high beam lights on the right counting from right to left (in positive y direction), starting with 0.

image::Grp_Light_Day_Right.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Corner_Left_<part_idx>_<corner_left_idx>

This group contains all parts of a corner light on the left side of the vehicle (part).
A corner light is a typically white light for lateral illumination in the direction of an intended turn or lane change.

The `<corner_left_idx>` is the index for all corner lights on the left counting from right to left (in positive y direction), starting with 0.

image::Grp_Light_Day_Left.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission in neutral position

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Corner_Right_<part_idx>_<corner_right_idx>

This group contains all parts of a corner light on the right side of the vehicle (part).
A corner light is a typically white light for lateral illumination in the direction of an intended turn or lane change.

The `<corner_right_idx>` is the index for all corner lights on the right counting from right to left (in positive y direction), starting with 0.

image::Grp_Light_Day_Right.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission in neutral position

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Position_Left_<part_idx>_<position_left_idx>

This group contains all parts of a position light on the left side of the vehicle (part).
Position lights are typically smaller, low-intensity, orange lights.

The `<position_left_idx>` is the index for all position lights on the left counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Position_Right_<part_idx>_<position_right_idx>

This group contains all parts of a position light on the right side of the vehicle (part).
Position lights are typically smaller, low-intensity, orange lights.

The `<position_right_idx>` is the index for all position lights on the right counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Park_Left_<part_idx>_<park_left_idx>

This group contains all parts of a parking light on the left side of the vehicle (part).

The `<park_left_idx>` is the index for all parking lights on the left counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Park_Right_<part_idx>_<park_right_idx>

This group contains all parts of a parking light on the right side of the vehicle (part).

The `<park_right_idx>` is the index for all parking lights on the right counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Indicator_Left_<part_idx>_<indicator_left_idx>

This group contains all parts of an indicator light on the left side of the vehicle (part).

The `<indicator_left_idx>` is the index for all indicator lights on the left counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Indicator_Right_<part_idx>_<indicator_right_idx>

This group contains all parts of an indicator light on the left side of the vehicle (part).

The `<indicator_right_idx>` is the index for all indicator lights on the right counting from right to left (in positive y direction), and from the front to the rear, starting with 0.


.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_License_Plate_<part_idx>_<license_plate_light_idx>

This group contains all parts of a license plate light of the vehicle (part).

The `<license_plate_light_idx>` is the index for all license plate lights counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure for the exemplary license plate light on the rear of the vehicle (part).

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Tail_Left_<part_idx>_<tail_left_idx>

This group contains all parts of a tail light on the left side of the vehicle (part).

The `<tail_left_idx>` is the index for all tail lights on the left counting from right to left (in positive y direction), starting with 0.

NOTE: Add a figure. This figure might be applicable to all lights on the rear left. I don't think we have to distinguish in the figures between the different kinds of lights.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Tail_Right_<part_idx>_<tail_right_idx>

This group contains all parts of a tail light on the right side of the vehicle (part).

The `<tail_right_idx>` is the index for all tail lights on the right counting from right to left (in positive y direction), starting with 0.

NOTE: Add a figure. This figure might be applicable to all lights on the rear right. I don't think we have to distinguish in the figures between the different kinds of lights.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Brake_Left_<part_idx>_<brake_left_idx>

This group contains all parts of a brake light on the left side of the vehicle (part).

The `<brake_left_idx>` is the index for all brake lights on the left counting from right to left (in positive y direction), starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Brake_Center_<part_idx>_<brake_center_idx>

This group contains all parts of a brake light in the center of the vehicle (part).

The `<brake_center_idx>` is the index for all brake lights in the center counting from right to left (in positive y direction), starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Brake_Right_<part_idx>_<brake_right_idx>

This group contains all parts of a brake light on the right side of the vehicle (part).

The `<brake_right_idx>` is the index for all brake lights on the right counting from right to left (in positive y direction), starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Reverse_Left_<part_idx>_<reverse_left_idx>

This group contains all parts of a reverse light on the left side of the vehicle (part).

The `<reverse_left_idx>` is the index for all reverse lights on the left counting from right to left (in positive y direction), starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Reverse_Right_<part_idx>_<reverse_right_idx>

This group contains all parts of a reverse light on the right side of the vehicle (part).

The `<reverse_right_idx>` is the index for all reverse lights on the right counting from right to left (in positive y direction), starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Fog_Left_<part_idx>_<fog_left_idx>

This group contains all parts of a fog light on the left side of the vehicle (part).

The `<fog_left_idx>` is the index for all fog lights on the left counting from right to left (in positive y direction), starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Fog_Right_<part_idx>_<fog_right_idx>

This group contains all parts of a fog light on the right side of the vehicle (part).

The `<fog_right_idx>` is the index for all fog lights on the right counting from right to left (in positive y direction), starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Warning_<part_idx>_<warning_idx>

This group contains all parts of a warning light of the vehicle (part).
Warning lights can be all kinds of emergency lights, hazard lights, etc.

The `<warning_idx>` is the index for all warning lights counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure on an exemplary rotating warning light on the roof the vehicle (part).

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, or forwards for rotating lights

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Side_Mounting_Left_<part_idx>_<side_mirror_mounting_left_idx> 

This group contains all parts of a mirror mounting on the left side of the vehicle (part).

The `<side_mirror_mounting_left_idx>` is the index for all mirror mountings on the left counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Base of the mirror mounting

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Side_View_Left_<part_idx>_<side_mirror_view_left_idx>

This group contains all parts of a mirror without the housing on the left side of the vehicle (part).

The `<side_mirror_view_left_idx>` is the index for all mirrors on the left counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the mirror surface

| *x-axis*
| Pointing outwards from the front of the mirror

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards along the mirror face
|===


== Grp_Mirror_Side_Mounting_Right_<part_idx>_<side_mirror_mounting_right_idx>

This group contains all parts of a mirror mounting on the right side of the vehicle (part).

The `<side_mirror_mounting_right_idx>` is the index for all mirror mountings on the right counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Base of the mirror mounting

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Side_View_Right_<part_idx>_<side_mirror_view_right_idx>

This group contains all parts of a mirror without the housing on the right side of the vehicle (part).

The `<side_mirror_view_right_idx>` is the index for all mirrors on the right counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the mirror surface

| *x-axis*
| Pointing outwards from the front of the mirror

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards along the mirror face
|===


== Grp_Mirror_Blindspot_Mounting_<part_idx>_<blindspot_mirror_mounting_idx>

This group contains all parts of a blindspot mirror mounting of the vehicle (part).

The `<blindspot_mirror_mounting_idx>` is the index for all blindspot mountings counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Base of the mirror mounting

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Blindspot_View_<part_idx>_<blindspot_mirror_view_idx>

This group contains all parts of a mirror without the housing of the vehicle (part).

The `<side_mirror_view_right_idx>` is the index for all blindspot mirrors counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the mirror surface

| *x-axis*
| Pointing outwards from the front of the mirror

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards along the mirror face
|===


== Grp_License_Plate_<part_idx>_<license_plate_idx>

This group contains all parts of a license plate of the vehicle (part).

The `<license_plate_idx>` is the index for all license plates counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the plate

| *x-axis*
| Pointing outwards from the front of the plate

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Convertible_Top_<part_idx>

This group contains all parts of a convertible top of the vehicle (part).

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle (part)

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Sensor_<part_idx>_<sensor_idx>

This group contains all parts of a perception sensor of the vehicle (part).
The geometry of a sensor can alternatively be placed in the Grp_Exterior_Static.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the sensor

| *x-axis*
| Pointing outwards from the sensor in the direction of its longitudinal axis

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing upwards in sensor coordinates
|===


== Grp_Interior_<part_idx>

This group contains all elements of the interior of the vehicle (part).
The interior is separated form the exterior to enable disabling or exchanging it in the simulation.

This group typically does not move in the simulation and therefore does not have its own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle (part)

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Interior_Static_<part_idx>

This group contains all static elements of the interior of the vehicle (part).
Static elements are geometry structures that have a fixed position and orientation relative to the origin on the vehicle (part) throughout a simulation.
They also do not change their state during the simulation, therefore lights are considered dynamic.

This group typically does not move in the simulation and therefore does not have its own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle (part)

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Interior_Dynamic_<part_idx>

This group contains all dynamic elements of the exterior of the vehicle (part).
Dynamic elements are geometry structures which position and orientation relative to the origin on the vehicle (part) might change throughout a simulation.
They may also change their state during the simulation, therefore lights are considered dynamic.

This group typically does not move in the simulation and therefore does not have its own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle (part)

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Steering_Wheel_<part_idx>

This group contains all elements of the steering wheel of the vehicle (part).

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the steering wheel

| *x-axis*
| Collinear with the steering column, pointing towards the axis

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards in neutral position
|===


== Grp_Eyepoint_<part_idx>_<eyepoint_idx>

This group contains is an empty element containing the origin of an average passenger of the vehicle (part).

The `<eyepoint_idx>` is the index for all eye points counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the eye view point

| *x-axis*
| Collinear with the view direction

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards in neutral position
|===


== Grp_Mirror_Rearview_Mounting_<part_idx>_<rearview_mirror_mounting_idx>

This group contains all parts of a rearview mirror mounting of the vehicle (part).

The `<rearview_mirror_mounting_idx>` is the index for all rearview mirrors mounting counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Base of the mirror mounting

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Rearview_View_<part_idx>_<rearview_mirror_view_idx>

This group contains all parts of a rearview mirror without the housing.

The `<rearview_mirror_view_idx>` is the index for all rearview mirrors counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the mirror surface

| *x-axis*
| Pointing outwards from the front of the mirror

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards along the mirror face
|===


== Grp_Seat_<part_idx>_<seat_idx>

This group contains all parts of a seat of the vehicle (part).

The seat position can be used for the placement of a human 3D model as a passenger.
Therefore, a bench is consists of multiple individual seats.

The `<seat_idx>` is the index for all seats counting from from the front to the rear and right to left (in positive y direction), starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the seat cushion.

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing in the direction of the seat

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===
