= Model structure

:home-path: ../..
:imagesdir: {home-path}/_images
:includedir: {home-path}/_images

== Structure overview

[plantuml]
----
legend
Root
|_ [[../geometry/object-classes.html#_grp_exterior Grp_Exterior]]
  |_ [[../geometry/object-classes.html#_grp_exterior_dynamic Grp_Exterior_Dynamic]]
    |_ [[../geometry/object-classes.html#_grp_convertible_top Grp_Convertible_Top]]
    |_ [[../geometry/object-classes.html#_grp_door_bottom_door_bottom_idx Grp_Door_Bottom_<door_bottom_idx>]]
    |_ [[../geometry/object-classes.html#_grp_door_front_door_front_idx Grp_Door_Front_<door_front_idx>]]
    |_ [[../geometry/object-classes.html#_grp_door_left_door_left_idx Grp_Door_Left_<door_left_idx>]]
      |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_mounting_blindspot_mirror_mounting_idx Grp_Mirror_Blindspot_Mounting_<blindspot_mirror_mounting_idx>]]
        |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_joint_blindspot_mirror_joint_idx Grp_Mirror_Blindspot_Joint_<blindspot_mirror_joint_idx>]]
          |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_view_blindspot_mirror_view_idx Grp_Mirror_Blindspot_View_<blindspot_mirror_view_idx>]]
      |_ [[../geometry/object-classes.html#_grp_mirror_side_mounting_left_side_mirror_mounting_left_id Grp_Mirror_Side_Mounting_Left_<side_mirror_mounting_left_idx>]]
        |_ [[../geometry/object-classes.html#_grp_mirror_side_joint_left_side_mirror_joint_left_idx Grp_Mirror_Side_Joint_Left_<side_mirror_joint_left_idx> ]]
          |_ [[../geometry/object-classes.html#_grp_mirror_side_view_left_side_mirror_view_left_idx Grp_Mirror_Side_View_Left_<side_mirror_view_left_idx> ]]
      |_ [[../geometry/object-classes.html#_grp_mirror_side_mounting_right_side_mirror_mounting_right_idx Grp_Mirror_Side_Mounting_Right_<side_mirror_mounting_right_idx>]]
        |_ [[../geometry/object-classes.html#_grp_mirror_side_joint_right_side_mirror_joint_right_idx Grp_Mirror_Side_Joint_Right_<side_mirror_joint_right_idx> ]]
          |_ [[../geometry/object-classes.html#_grp_mirror_side_view_right_side_mirror_view_right_idx Grp_Mirror_Side_View_Right_<side_mirror_view_right_idx> ]]
    |_ [[../geometry/object-classes.html#_grp_door_rear_door_rear_idx Grp_Door_Rear_<door_rear_idx>]]
    |_ [[../geometry/object-classes.html#_grp_door_right_door_right_idx Grp_Door_Right_<door_right_idx>]]
      |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_mounting_blindspot_mirror_mounting_idx Grp_Mirror_Blindspot_Mounting_<blindspot_mirror_mounting_idx>]]
        |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_joint_blindspot_mirror_joint_idx Grp_Mirror_Blindspot_Joint_<blindspot_mirror_joint_idx>]]
          |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_view_blindspot_mirror_view_idx Grp_Mirror_Blindspot_View_<blindspot_mirror_view_idx>]]
      |_ [[../geometry/object-classes.html#_grp_mirror_side_mounting_left_side_mirror_mounting_left_id Grp_Mirror_Side_Mounting_Left_<side_mirror_mounting_left_idx>]]
        |_ [[../geometry/object-classes.html#_grp_mirror_side_joint_left_side_mirror_joint_left_idx Grp_Mirror_Side_Joint_Left_<side_mirror_joint_left_idx> ]]
          |_ [[../geometry/object-classes.html#_grp_mirror_side_view_left_side_mirror_view_left_idx Grp_Mirror_Side_View_Left_<side_mirror_view_left_idx> ]]
      |_ [[../geometry/object-classes.html#_grp_mirror_side_mounting_right_side_mirror_mounting_right_idx Grp_Mirror_Side_Mounting_Right_<side_mirror_mounting_right_idx>]]
        |_ [[../geometry/object-classes.html#_grp_mirror_side_joint_right_side_mirror_joint_right_idx Grp_Mirror_Side_Joint_Right_<side_mirror_joint_right_idx> ]]
          |_ [[../geometry/object-classes.html#_grp_mirror_side_view_right_side_mirror_view_right_idx Grp_Mirror_Side_View_Right_<side_mirror_view_right_idx> ]]
    |_ [[../geometry/object-classes.html#_grp_door_top_door_top_idx Grp_Door_Top_<door_top_idx>]]
    |_ [[../geometry/object-classes.html#_grp_license_plate_license_plate_idx Grp_License_Plate_<license_plate_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_brake_center_brake_center_idx Grp_Light_Brake_Center_<brake_center_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_brake_left_brake_left_idx Grp_Light_Brake_Left_<brake_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_brake_right_brake_right_idx Grp_Light_Brake_Right_<brake_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_corner_left_corner_left_idx Grp_Light_Corner_Left_<corner_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_corner_right_corner_right_idx Grp_Light_Corner_Right_<corner_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_day_left_day_left_idx Grp_Light_Day_Left_<day_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_day_right_day_right_idx Grp_Light_Day_Right_<day_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_fog_left_fog_left_idx Grp_Light_Fog_Left_<fog_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_fog_right_fog_right_idx Grp_Light_Fog_Right_<fog_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_high_beam_left_high_beam_left_idx Grp_Light_High_Beam_Left_<high_beam_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_high_beam_right_high_beam_right_idx Grp_Light_High_Beam_Right_<high_beam_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_indicator_left_indicator_left_idx Grp_Light_Indicator_Left_<indicator_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_indicator_right_indicator_right_idx Grp_Light_Indicator_Right_<indicator_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_license_plate_license_plate_light_idx Grp_Light_License_Plate_<license_plate_light_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_low_beam_left_low_beam_left_idx Grp_Light_Low_Beam_Left_<low_beam_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_low_beam_right_low_beam_right_idx Grp_Light_Low_Beam_Right_<low_beam_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_park_left_park_left_idx Grp_Light_Park_Left_<park_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_park_right_park_right_idx Grp_Light_Park_Right_<park_right_idx> ]]
    |_ [[../geometry/object-classes.html#_grp_light_position_left_position_left_idx Grp_Light_Position_Left_<position_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_position_right_position_right_idx Grp_Light_Position_Right_<position_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_reverse_left_reverse_left_idx Grp_Light_Reverse_Left_<reverse_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_reverse_right_reverse_right_idx Grp_Light_Reverse_Right_<reverse_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_tail_left_tail_left_idx Grp_Light_Tail_Left_<tail_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_tail_right_tail_right_idx Grp_Light_Tail_Right_<tail_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_warning_warning_idx Grp_Light_Warning_<warning_idx>]]
    |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_mounting_blindspot_mirror_mounting_idx Grp_Mirror_Blindspot_Mounting_<blindspot_mirror_mounting_idx>]]
      |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_joint_blindspot_mirror_joint_idx Grp_Mirror_Blindspot_Joint_<blindspot_mirror_joint_idx>]]
        |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_view_blindspot_mirror_view_idx Grp_Mirror_Blindspot_View_<blindspot_mirror_view_idx>]]
    |_ [[../geometry/object-classes.html#_grp_mirror_side_mounting_left_side_mirror_mounting_left_id Grp_Mirror_Side_Mounting_Left_<side_mirror_mounting_left_idx>]]
      |_ [[../geometry/object-classes.html#_grp_mirror_side_joint_left_side_mirror_joint_left_idx Grp_Mirror_Side_Joint_Left_<side_mirror_joint_left_idx> ]]
        |_ [[../geometry/object-classes.html#_grp_mirror_side_view_left_side_mirror_view_left_idx Grp_Mirror_Side_View_Left_<side_mirror_view_left_idx> ]]
    |_ [[../geometry/object-classes.html#_grp_mirror_side_mounting_right_side_mirror_mounting_right_idx Grp_Mirror_Side_Mounting_Right_<side_mirror_mounting_right_idx>]]
      |_ [[../geometry/object-classes.html#_grp_mirror_side_joint_right_side_mirror_joint_right_idx Grp_Mirror_Side_Joint_Right_<side_mirror_joint_right_idx> ]]
        |_ [[../geometry/object-classes.html#_grp_mirror_side_view_right_side_mirror_view_right_idx Grp_Mirror_Side_View_Right_<side_mirror_view_right_idx> ]]
    |_ [[../geometry/object-classes.html#_grp_sensor_sensor_idx Grp_Sensor_<sensor_idx>]]
    |_ [[../geometry/object-classes.html#_grp_wheel_axle_idx_wheel_idx Grp_Wheel_<axle_idx>_<wheel_idx>]]
      |_ [[../geometry/object-classes.html#_grp_wheel_steering_axle_idx_wheel_idx Grp_Wheel_Steering_<axle_idx>_<wheel_idx>]]
      |_ [[../geometry/object-classes.html#_grp_wheel_steering_rotating_axle_idx_wheel_idx Grp_Wheel_Steering_Rotating_<axle_idx>_<wheel_idx>]]
  |_ [[../geometry/object-classes.html#_grp_exterior_static Grp_Exterior_Static]]
|_ [[../geometry/object-classes.html#_grp_interior Grp_Interior]]
  |_ [[../geometry/object-classes.html#_grp_interior_dynamic Grp_Interior_Dynamic]]
    |_ [[../geometry/object-classes.html#_grp_eyepoint_eyepoint_idx Grp_Eyepoint_<eyepoint_idx>]]
    |_ [[../geometry/object-classes.html#_grp_mirror_rearview_mounting_rearview_mirror_mounting_idx Grp_Mirror_Rearview_Mounting_<rearview_mirror_mounting_idx>]]
      |_ [[../geometry/object-classes.html#_grp_mirror_rearview_joint_rearview_mirror_joint_idx Grp_Mirror_Rearview_Joint_<rearview_mirror_joint_idx>]]
        |_ [[../geometry/object-classes.html#_grp_mirror_rearview_view_rearview_mirror_view_idx Grp_Mirror_Rearview_View_<rearview_mirror_view_idx>]]
    |_ [[../geometry/object-classes.html#_grp_seat_seat_idx Grp_Seat_<seat_idx>]]
    |_ [[../geometry/object-classes.html#_grp_steering_wheel Grp_Steering_Wheel]]
  |_ [[../geometry/object-classes.html#_grp_interior_static Grp_Interior_Static]]
|_ [[../geometry/object-classes.html#_grp_vehicle_part Optional Grp_Vehicle_Part]]
end legend
----


== Grp_Exterior

This group contains all parts of the vehicle's exterior.

Typically, this group do not move in the simulation and therefore do not have their own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Exterior_Dynamic

This group contains all dynamic parts of the vehicle's exterior.

Dynamic parts are geometric structures whose position and orientation relative to the vehicle's origin may change throughout a simulation.
They may also change their state during the simulation, which is why lights are considered dynamic.

Typically, this group does not move in the simulation and therefore does not have its own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Convertible_Top

This group contains all parts of a vehicle's convertible top.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Door_Bottom_<door_bottom_idx>

This group contains all parts of a door located at the bottom of the vehicle, including its interior parts, as they move together as a unit.

`<door_bottom_idx>` denotes the index of doors at the bottom. The index entries
are sorted from front to rear, starting with 0.

NOTE: Add a figure with a hatch on the bottom.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing along the closed door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis, pointing in the direction that enables the door to open with a positive rotation around the z-axis
|===

== Grp_Door_Front_<door_front_idx>

This group contains all parts of a door located at the front of the vehicle, such as the engine cover. It also includes the door's interior parts, as they move together as a single unit.

`<door_front_idx>` denotes the index of front doors. The index entries are
sorted from right to left in positive y-direction, starting with 0.

image::Grp_Door_Front.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing along the closed door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis, pointing in the direction that enables the door to open with a positive rotation around the z-axis
|===


== Grp_Door_Left_<door_left_idx>

This group contains all parts of a door located at the left side of the vehicle, including its interior parts, as they move together as a unit.

`<door_left_idx>` denotes the index of doors on the left side. The index entries
are sorted from front to rear, starting with 0.

image::Grp_Door_Left.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing along the closed door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis, pointing in the direction that enables the door to open with a positive rotation around the z-axis
|===

== Grp_Door_Rear_<door_rear_idx>

This group contains all parts of a door located at the rear of the vehicle, such as the trunklid. It also includes the door's interior parts, as they move together as a single unit.

`<door_rear_idx>` denotes the index of rear doors. The index entries are sorted
from right to left in positive y-direction, starting with 0.

image::Grp_Door_Rear.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing along the closed door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis, pointing in the direction that enables the door to open with a positive rotation around the z-axis
|===


== Grp_Door_Right_<door_right_idx>

This group contains all parts of a door located at the right side of the vehicle, including its interior parts, as they move together as a unit.

`<door_right_idx>` denotes the index of doors on the right side. The index entries
are sorted from front to rear, starting with 0.

image::Grp_Door_Right.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing along the closed door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis, pointing in the direction that enables the door to open with a positive rotation around the z-axis
|===




== Grp_Door_Top_<door_top_idx>

This group contains all parts of a door located at the top of the vehicle, including its interior parts, as they move together as a unit.

`<door_top_idx>` denotes the index of doors on the top of the vehicle. The index entries
are sorted from front to rear, starting with 0.

image::Grp_Door_Top.svg[, 1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing along the closed door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis, pointing in the direction that enables the door to open with a positive rotation around the z-axis
|===

== Grp_License_Plate_<license_plate_idx>

This group contains all parts of the vehicle’s license plate.

`<license_plate_idx>` denotes the index of license plates. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the plate

| *x-axis*
| Pointing outwards from the front of the license plate

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Light_Brake_Center_<brake_center_idx>

This group contains all parts of a brake light located at the center of the vehicle.

`<brake_center_idx>` denotes the index of brake lights in the center. The index entries
are sorted from right to left in positive y-direction, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Light_Brake_Left_<brake_left_idx>

This group contains all parts of a brake light located at the left side of the vehicle.

`<brake_left_idx>` denotes the index of brake lights on the left side. The index entries
are sorted from right to left in positive y-direction, starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===



== Grp_Light_Brake_Right_<brake_right_idx>

This group contains all parts of a brake light located at the right side of the vehicle.

`<brake_right_idx>` denotes the index of brake lights on the right side. The index entries
are sorted from right to left in positive y-direction, starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Corner_Left_<corner_left_idx>

This group contains all parts of a corner light on the vehicle's left side.
A corner light is typically a white light that provides side illumination in the direction of a turn or lane change.

`<corner_left_idx>` denotes the index of corner lights on the left side. The index entries
are sorted from right to left in positive y-direction, starting with 0.

image::Grp_Light_Day_Left.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission in neutral position

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Corner_Right_<corner_right_idx>

This group contains all parts of a corner light on the vehicle's right side.
A corner light is typically a white light that provides side illumination in the direction of a turn or lane change.

`<corner_right_idx>` denotes the index of corner lights on the right side. The index entries
are sorted from right to left in positive y-direction, starting with 0.

image::Grp_Light_Day_Right.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission in neutral position

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Day_Left_<day_left_idx>

This group contains all parts of the daytime running light on the vehicle's left side.

`<day_left_idx>` denotes the index of daytime running lights on the left side. The index entries
are sorted from right to left in positive y-direction, starting with 0.

//NOTE: Add a figure. This figure might ba applicable to all lights on the front left. I don't think we have to distinguish in the figures between the different kinds of lights.
image::Grp_Light_Day_Left.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Day_Right_<day_right_idx>

This group contains all parts of the daytime running light on the vehicle's right side.

`<day_right_idx>` denotes the index of daytime running lights on the right side. The index entries
are sorted from right to left in positive y-direction, starting with 0.

//NOTE: Add a figure. This figure might be applicable to all lights on the front right. I don't think we have to distinguish in the figures between the different kinds of lights.
image::Grp_Light_Day_Right.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Fog_Left_<fog_left_idx>

This group contains all parts of a fog light on the vehicle's left side.

`<fog_left_idx>` denotes the index of fog lights on the left side. The index entries
are sorted from right to left in positive y-direction, starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Fog_Right_<fog_right_idx>

This group contains all parts of a fog light on the vehicle's right side.

`<fog_right_idx>` denotes the index of fog lights on the right side. The index entries
are sorted from right to left in positive y-direction, starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Light_High_Beam_Left_<high_beam_left_idx>

This group contains all parts of a high beam light on the vehicle's left side.

`<high_beam_left_idx>` denotes the index of high beam lights on the left side. The index entries
are sorted from right to left in positive y-direction, starting with 0.

image::Grp_Light_Day_Left.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_High_Beam_Right_<high_beam_right_idx>

This group contains all parts of a high beam light on the vehicle's right side.

`<high_beam_right_idx>` denotes the index of high beam lights on the right side. The index entries
are sorted from right to left in positive y-direction, starting with 0.

image::Grp_Light_Day_Right.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Indicator_Left_<indicator_left_idx>

This group contains all parts of an indicator light on the vehicle's left side.

`<indicator_left_idx>` denotes the index of indicator lights on the left side. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Indicator_Right_<indicator_right_idx>

This group contains all parts of an indicator light on the vehicle's right side.

`<indicator_right_idx>` denotes the index of indicator lights on the right side. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Light_License_Plate_<license_plate_light_idx>

This group contains all parts of the vehicle's license plate light.

`<license_plate_light_idx>` denotes the index of license plate lights. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

NOTE: Add a figure for the exemplary license plate light on the rear of the vehicle.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Low_Beam_Left_<low_beam_left_idx>

This group contains all parts of a low beam light on the vehicle's left side.

`<low_beam_left_idx>` denotes the index of low beam lights on the left side. The index entries
are sorted from right to left in positive y-direction, starting with 0.

image::Grp_Light_Day_Left.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Low_Beam_Right_<low_beam_right_idx>

This group contains all parts of a low beam light on the vehicle's right side.

`<low_beam_right_idx>` denotes the index of low beam lights on the right side. The index entries
are sorted from right to left in positive y-direction, starting with 0.

image::Grp_Light_Day_Right.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Park_Left_<park_left_idx>

This group contains all parts of a parking light on the vehicle's left side.

`<park_left_idx>` denotes the index of parking lights on the left side. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Park_Right_<park_right_idx>

This group contains all parts of a parking light on the vehicle's right side.

`<park_right_idx>` denotes the index of parking lights on the right side. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Light_Position_Left_<position_left_idx>

This group contains all parts of a position light on the vehicle's left side.
Position lights are usually small, low-intensity, and orange.

`<position_left_idx>` denotes the index of position lights on the left side. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Position_Right_<position_right_idx>

This group contains all parts of a position light on the vehicle's right side.
Position lights are usually small, low-intensity, and orange.

`<position_right_idx>` denotes the index of position lights on the right side. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Light_Reverse_Left_<reverse_left_idx>

This group contains all parts of a reverse light on the vehicle's left side.

`<reverse_left_idx>` denotes the index of reverse lights on the left side. The index entries
are sorted from right to left in positive y-direction, starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Reverse_Right_<reverse_right_idx>

This group contains all parts of a reverse light on the vehicle's right side.

`<reverse_right_idx>` denotes the index of reverse lights on the right side. The index entries
are sorted from right to left in positive y-direction, starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Tail_Left_<tail_left_idx>

This group contains all parts of a tail light on the vehicle's left side.

`<tail_left_idx>` denotes the index of tail lights on the left side. The index entries
are sorted from right to left in positive y-direction, starting with 0.

NOTE: Add a figure. This figure might be applicable to all lights on the rear left. I don't think we have to distinguish in the figures between the different kinds of lights.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Tail_Right_<tail_right_idx>

This group contains all parts of a tail light on the vehicle's right side.

`<tail_right_idx>` denotes the index of tail lights on the right side. The index entries
are sorted from right to left in positive y-direction, starting with 0.

NOTE: Add a figure. This figure might be applicable to all lights on the rear right. I don't think we have to distinguish in the figures between the different kinds of lights.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Warning_<warning_idx>

This group contains all parts of the vehicle's warning light.
Warning lights can include various emergency lights, hazard lights, and more.

`<warning_idx>` denotes the index of warning lights. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

NOTE: Add a figure on an exemplary rotating warning light on the roof the vehicle.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, or forwards for rotating lights

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Blindspot_Joint_Left_<blindspot_mirror_joint_idx>

This group contains all parts of the movable structure that holds the blindspot
mirror. The blindspot mirror automatically adjusts when the angle of the
blindspot joint changes.

It is a child node of the corresponding mirror mounting group.

`<blindspot_mirror_joint_idx>` denotes the index of blindspot mirror joints. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Joint of the movable structure of a mirror

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Blindspot_Mounting_<blindspot_mirror_mounting_idx>

This group contains all parts of the vehicle's blindspot mirror mounting.

It is a child node of `<Grp_Exterior_Dynamic>` if mounted directly to the
vehicle body, or a child node of either `<Grp_Door_Left>` or `<Grp_Door_Right>` if
mounted to the door.

`<blindspot_mirror_mounting_idx>` denotes the index of blindspot mirror mountings. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

The index is used consistently, regardless of whether the mirror is mounted to
the door or to the vehicle body.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Base of the mirror mounting

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Blindspot_View_<blindspot_mirror_view_idx>

This group is an empty node that represents the view direction of the mirror
glass on a blindspot mirror.

It is a child node of the corresponding mirror joint group.

`<blindspot_mirror_view_idx>` denotes the index of blindspot mirrors. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the mirror glass surface

| *x-axis*
| Pointing outwards from the mirror glass, aligned with the surface normal

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards along the face of the mirror glass
|===


== Grp_Mirror_Side_Joint_Left_<side_mirror_joint_left_idx>

This group contains all parts of the movable structure that holds the mirror on
the vehicle's left side. The mirror automatically adjusts when the angle of the
joint changes.

It is a child node of the corresponding mirror mounting group.

`<side_mirror_joint_left_idx>` denotes the index of side mirror joints on the
left side. The index entries are sorted from right to left in positive
y-direction, and from front to rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Joint of the movable structure of a mirror

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Side_Joint_Right_<side_mirror_joint_right_idx>

This group contains all parts of the movable structure that holds the mirror on
the vehicle's left side. The mirror automatically adjusts when the angle of the
joint changes.

It is a child node of the corresponding mirror mounting group.

`<side_mirror_joint_right_idx>` denotes the index of side mirror joints on the
right side. The index entries are sorted from right to left in positive
y-direction, and from front to rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Joint of the movable structure of a mirror

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Side_Mounting_Left_<side_mirror_mounting_left_idx>

This group contains all parts of the side mirror on the vehicle's left side.

It is a child node of `<Grp_Exterior_Dynamic>` if mounted directly to the
vehicle body, or a child node of either `<Grp_Door_Left>` or `<Grp_Door_Right>` if
mounted to the door.

`<side_mirror_mounting_left_idx>` denotes the index of side mirrors on the left side. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

The index is used consistently, regardless of whether the mirror is mounted to
the door or to the vehicle body.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Base of the mirror mounting

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Side_Mounting_Right_<side_mirror_mounting_right_idx>

This group contains all parts of the side mirror on the vehicle's right side.

It is a child node of `<Grp_Exterior_Dynamic>` if mounted directly to the
vehicle body, or a child node of either `<Grp_Door_Left>` or `<Grp_Door_Right>` if mounted
to the door.

`<side_mirror_mounting_right_idx>` denotes the index of side mirrors on the
right side. The index entries are sorted from right to left in positive
y-direction, and from front to rear, starting with 0.

The index is used consistently, regardless of whether the mirror is mounted to
the door or to the vehicle body.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Base of the mirror mounting

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Side_View_Left_<side_mirror_view_left_idx>

This group is an empty node that represents the view direction of the mirror
glass on a side mirror on the left side of the vehicle.

It is a child node of the corresponding mirror joint group.

`<side_mirror_view_left_idx>` denotes the index of mirror glasses on the left side. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.


NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the mirror glass surface

| *x-axis*
| Pointing outwards from the mirror glass, aligned with the surface normal

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards along the face of the mirror glass
|===


== Grp_Mirror_Side_View_Right_<side_mirror_view_right_idx>

This group is an empty node that represents the view direction of the mirror
glass on a side mirror on the right side of the vehicle.

It is a child node of the corresponding mirror joint group.

`<side_mirror_view_right_idx>` denotes the index of mirror glasses on the right side. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the mirror glass surface

| *x-axis*
| Pointing outwards from the mirror glass, aligned with the surface normal

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards along the face of the mirror glass
|===


== Grp_Sensor_<sensor_idx>

This group contains all parts of the vehicle's perception sensors.

The sensor's geometry can also be placed in <Grp_Exterior_Static>.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the sensor

| *x-axis*
| Pointing outwards from the sensor in the direction of its longitudinal axis

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing upwards in sensor coordinates
|===

== Grp_Wheel_<axle_idx>_<wheel_idx>

This group contains all geometries of a single wheel assembly, which may consist of the tire, rim, brake caliper, and so on.

`<axle_idx>` denotes the index of the axle to which the wheel is mounted,
counting from front to rear, starting with 0.

`<wheel_idx>` denotes the index of the wheel on the specified axle, counting from right to left in positive y-direction, starting with 0.
For example, the wheel on the front left of a standard vehicle would be labeled `Grp_Wheel_0_1`.

Wheel steering is represented by rotation around the z-axis.
Wheel camber is defined by a rotation around the x-axis.
Suspension deflection is represented by translation along the z-axis.
Zero rotation and translation around all axles are defined under neutral load conditions.
In the 3D model, both caster and camber angles are ignored.

image::Grp_Wheel.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the wheel

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Wheel_Steering_<axle_idx>_<wheel_idx>

This group contains all components of the wheel assembly that follow the steering motion but not the wheel's rotation, such as brake calipers.

The indices are the same as in the parent group.

This group typically does not move independently in the simulation, as it moves with the parent transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the wheel

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Wheel_Steering_Rotating_<axle_idx>_<wheel_idx>

This group contains all components of the wheel assembly that follow the steering motion as well as the rotation of the wheel, such as tire and rim.

The indices are the same as in the parent group.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the wheel

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing towards the door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Exterior_Static

This group contains all static parts of the vehicle's exterior.
Static elements are geometric structures that have a fixed position and
orientation relative to the vehicle's origin throughout the simulation.

In contrast to lights, which change their state depending on whether they are
switched on or off, static elements never change state during the simulation.

This group typically does not move in the simulation and therefore does not have its own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Interior

This group contains all parts of the vehicle's interior.
The interior is separated from the exterior to allow for disabling or exchanging it in the simulation.

This group typically does not move in the simulation and therefore does not have its own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Interior_Dynamic

This group contains all dynamic parts of the vehicle's interior.
Dynamic elements are geometric structures whose position and orientation relative to the vehicle's origin may change throughout the simulation.

They may also change their state during the simulation. Examples of dynamic elements are lights, which can be switched on and off.
This group typically does not move in the simulation and therefore does not have its own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Eyepoint_<eyepoint_idx>

This group contains an empty element that contains the origin of an average passenger in the vehicle.

`<eyepoint_idx>` denotes the index of eye points. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the eye view point

| *x-axis*
| Collinear with the view direction

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards in neutral position
|===


== Grp_Mirror_Rearview_Joint_Left_<rearview_mirror_joint_idx>

This group contains all parts of the movable structure that holds the rearview
mirror. The mirror automatically adjusts when the angle of the joint changes.

`<rearview_mirror_joint_idx>` denotes the index of rearview mirror joints. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Joint of the movable structure of a mirror

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Rearview_Mounting_<rearview_mirror_mounting_idx>

This group contains all parts of a vehicle's rearview mirror mounting.

`<rearview_mirror_mounting_idx>` denotes the index of rearview mirror mountings. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

The index is used consistently, regardless of whether the mirror is mounted to
the door or to the vehicle body.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Base of the mirror mounting

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Rearview_View_<rearview_mirror_view_idx>

This group is an empty node that represents the view direction of the mirror
glass on a rearview mirror.

It is a child node of the corresponding mirror joint group.

`<rearview_mirror_view_idx>` denotes the index of rearview mirrors. The index entries
are sorted from right to left in positive y-direction, and from front to rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the mirror glass surface

| *x-axis*
| Pointing outwards from the mirror glass, aligned with the surface normal

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards along the face of the mirror glass
|===


== Grp_Seat_<seat_idx>

This group contains all parts of the vehicles's seats.

The seat position can be used to place a human 3D model as a passenger.
Therefore, a bench consists of multiple individual seats.

`<seat_idx>` denotes the index of seats. The index entries
are sorted from right to left in positive y-direction, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the seat cushion.

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing in the direction of the seat

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Steering_Wheel

This group contains all elements of the vehicles's steering wheel.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the steering wheel

| *x-axis*
| Collinear with the steering column, pointing towards the axis

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards in neutral position
|===


== Grp_Interior_Static

This group contains all static parts of the vehicle's interior.
Static elements are geometric structures that have a fixed position and orientation relative to the vehicle's origin throughout the simulation.

In contrast to lights, which change their state depending on whether they are
switched on or off, static elements never change state during the simulation.

This group typically does not move in the simulation and therefore does not have its own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle

| *x-axis*
| Collinear with the vehicle's longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Vehicle_Part

One or more optional vehicle parts may be added to the main vehicle structure.

A vehicle part is a large component of a vehicle that moves in a slightly
different direction than other parts, for example, the vehicle part follows an
individual path during turns.

A vehicle may have multiple vehicle parts at the same hierarchy level or in a parent-child relationship.
This typically applies to articulated vehicles, such as a front loader with a hinged axis or an articulated bus with a hinge in the middle, and may also apply to construction vehicles.
When a vehicle part can be detached, like a trailer, it is treated as a separate object, not as a vehicle part.

The child nodes of a vehicle part may follow the same structure as the main vehicle. For example, if a vehicle part has lights, they may use the same structure and naming conventions as those on the main vehicle.

Standard passenger vehicles do not have separate parts.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the joint to the main vehicle or the parent.

| *x-axis*
| Collinear with the parts longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===