= Model structure

:home-path: ../..
:imagesdir: {home-path}/_images
:includedir: {home-path}/_images

== Structure overview

[plantuml]
----
legend
Root
|_ [[../geometry/object-classes.html#_grp_exterior Grp_Exterior]]
  |_ [[../geometry/object-classes.html#_grp_exterior_dynamic Grp_Exterior_Dynamic]]
    |_ [[../geometry/object-classes.html#_grp_convertible_top Grp_Convertible_Top]]
    |_ [[../geometry/object-classes.html#_grp_door_bottom_door_bottom_idx Grp_Door_Bottom_<door_bottom_idx>]]      
    |_ [[../geometry/object-classes.html#_grp_door_front_door_front_idx Grp_Door_Front_<door_front_idx>]]
    |_ [[../geometry/object-classes.html#_grp_door_left_door_left_idx Grp_Door_Left_<door_left_idx>]]
      |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_mounting_blindspot_mirror_mounting_idx Grp_Mirror_Blindspot_Mounting_<blindspot_mirror_mounting_idx>]]
        |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_joint_blindspot_mirror_joint_idx Grp_Mirror_Blindspot_Joint_<blindspot_mirror_joint_idx>]] 
          |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_view_blindspot_mirror_view_idx Grp_Mirror_Blindspot_View_<blindspot_mirror_view_idx>]] 
      |_ [[../geometry/object-classes.html#_grp_mirror_side_mounting_left_side_mirror_mounting_left_id Grp_Mirror_Side_Mounting_Left_<side_mirror_mounting_left_idx>]]
        |_ [[../geometry/object-classes.html#_grp_mirror_side_joint_left_side_mirror_joint_left_idx Grp_Mirror_Side_Joint_Left_<side_mirror_joint_left_idx> ]]
          |_ [[../geometry/object-classes.html#_grp_mirror_side_view_left_side_mirror_view_left_idx Grp_Mirror_Side_View_Left_<side_mirror_view_left_idx> ]]
      |_ [[../geometry/object-classes.html#_grp_mirror_side_mounting_right_side_mirror_mounting_right_idx Grp_Mirror_Side_Mounting_Right_<side_mirror_mounting_right_idx>]]
        |_ [[../geometry/object-classes.html#_grp_mirror_side_joint_right_side_mirror_joint_right_idx Grp_Mirror_Side_Joint_Right_<side_mirror_joint_right_idx> ]]   
          |_ [[../geometry/object-classes.html#_grp_mirror_side_view_right_side_mirror_view_right_idx Grp_Mirror_Side_View_Right_<side_mirror_view_right_idx> ]]
    |_ [[../geometry/object-classes.html#_grp_door_rear_door_rear_idx Grp_Door_Rear_<door_rear_idx>]]
    |_ [[../geometry/object-classes.html#_grp_door_right_door_right_idx Grp_Door_Right_<door_right_idx>]]
      |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_mounting_blindspot_mirror_mounting_idx Grp_Mirror_Blindspot_Mounting_<blindspot_mirror_mounting_idx>]]
        |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_joint_blindspot_mirror_joint_idx Grp_Mirror_Blindspot_Joint_<blindspot_mirror_joint_idx>]] 
          |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_view_blindspot_mirror_view_idx Grp_Mirror_Blindspot_View_<blindspot_mirror_view_idx>]]
      |_ [[../geometry/object-classes.html#_grp_mirror_side_mounting_left_side_mirror_mounting_left_id Grp_Mirror_Side_Mounting_Left_<side_mirror_mounting_left_idx>]]
        |_ [[../geometry/object-classes.html#_grp_mirror_side_joint_left_side_mirror_joint_left_idx Grp_Mirror_Side_Joint_Left_<side_mirror_joint_left_idx> ]]
          |_ [[../geometry/object-classes.html#_grp_mirror_side_view_left_side_mirror_view_left_idx Grp_Mirror_Side_View_Left_<side_mirror_view_left_idx> ]]
      |_ [[../geometry/object-classes.html#_grp_mirror_side_mounting_right_side_mirror_mounting_right_idx Grp_Mirror_Side_Mounting_Right_<side_mirror_mounting_right_idx>]]
        |_ [[../geometry/object-classes.html#_grp_mirror_side_joint_right_side_mirror_joint_right_idx Grp_Mirror_Side_Joint_Right_<side_mirror_joint_right_idx> ]]
          |_ [[../geometry/object-classes.html#_grp_mirror_side_view_right_side_mirror_view_right_idx Grp_Mirror_Side_View_Right_<side_mirror_view_right_idx> ]]
    |_ [[../geometry/object-classes.html#_grp_door_top_door_top_idx Grp_Door_Top_<door_top_idx>]]
    |_ [[../geometry/object-classes.html#_grp_license_plate_license_plate_idx Grp_License_Plate_<license_plate_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_brake_center_brake_center_idx Grp_Light_Brake_Center_<brake_center_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_brake_left_brake_left_idx Grp_Light_Brake_Left_<brake_left_idx>]]      
    |_ [[../geometry/object-classes.html#_grp_light_brake_right_brake_right_idx Grp_Light_Brake_Right_<brake_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_corner_left_corner_left_idx Grp_Light_Corner_Left_<corner_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_corner_right_corner_right_idx Grp_Light_Corner_Right_<corner_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_day_left_day_left_idx Grp_Light_Day_Left_<day_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_day_right_day_right_idx Grp_Light_Day_Right_<day_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_fog_left_fog_left_idx Grp_Light_Fog_Left_<fog_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_fog_right_fog_right_idx Grp_Light_Fog_Right_<fog_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_high_beam_left_high_beam_left_idx Grp_Light_High_Beam_Left_<high_beam_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_high_beam_right_high_beam_right_idx Grp_Light_High_Beam_Right_<high_beam_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_indicator_left_indicator_left_idx Grp_Light_Indicator_Left_<indicator_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_indicator_right_indicator_right_idx Grp_Light_Indicator_Right_<indicator_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_license_plate_license_plate_light_idx Grp_Light_License_Plate_<license_plate_light_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_low_beam_left_low_beam_left_idx Grp_Light_Low_Beam_Left_<low_beam_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_low_beam_right_low_beam_right_idx Grp_Light_Low_Beam_Right_<low_beam_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_park_left_park_left_idx Grp_Light_Park_Left_<park_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_park_right_park_right_idx Grp_Light_Park_Right_<park_right_idx> ]]
    |_ [[../geometry/object-classes.html#_grp_light_position_left_position_left_idx Grp_Light_Position_Left_<position_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_position_right_position_right_idx Grp_Light_Position_Right_<position_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_reverse_left_reverse_left_idx Grp_Light_Reverse_Left_<reverse_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_reverse_right_reverse_right_idx Grp_Light_Reverse_Right_<reverse_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_tail_left_tail_left_idx Grp_Light_Tail_Left_<tail_left_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_tail_right_tail_right_idx Grp_Light_Tail_Right_<tail_right_idx>]]
    |_ [[../geometry/object-classes.html#_grp_light_warning_warning_idx Grp_Light_Warning_<warning_idx>]]
    |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_mounting_blindspot_mirror_mounting_idx Grp_Mirror_Blindspot_Mounting_<blindspot_mirror_mounting_idx>]]
      |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_joint_blindspot_mirror_joint_idx Grp_Mirror_Blindspot_Joint_<blindspot_mirror_joint_idx>]] 
        |_ [[../geometry/object-classes.html#_grp_mirror_blindspot_view_blindspot_mirror_view_idx Grp_Mirror_Blindspot_View_<blindspot_mirror_view_idx>]] 
    |_ [[../geometry/object-classes.html#_grp_mirror_side_mounting_left_side_mirror_mounting_left_id Grp_Mirror_Side_Mounting_Left_<side_mirror_mounting_left_idx>]]
      |_ [[../geometry/object-classes.html#_grp_mirror_side_joint_left_side_mirror_joint_left_idx Grp_Mirror_Side_Joint_Left_<side_mirror_joint_left_idx> ]]
        |_ [[../geometry/object-classes.html#_grp_mirror_side_view_left_side_mirror_view_left_idx Grp_Mirror_Side_View_Left_<side_mirror_view_left_idx> ]]
    |_ [[../geometry/object-classes.html#_grp_mirror_side_mounting_right_side_mirror_mounting_right_idx Grp_Mirror_Side_Mounting_Right_<side_mirror_mounting_right_idx>]]
      |_ [[../geometry/object-classes.html#_grp_mirror_side_joint_right_side_mirror_joint_right_idx Grp_Mirror_Side_Joint_Right_<side_mirror_joint_right_idx> ]]   
        |_ [[../geometry/object-classes.html#_grp_mirror_side_view_right_side_mirror_view_right_idx Grp_Mirror_Side_View_Right_<side_mirror_view_right_idx> ]]          
    |_ [[../geometry/object-classes.html#_grp_sensor_sensor_idx Grp_Sensor_<sensor_idx>]]
    |_ [[../geometry/object-classes.html#_grp_wheel_axle_idx_wheel_idx Grp_Wheel_<axle_idx>_<wheel_idx>]]
      |_ [[../geometry/object-classes.html#_grp_wheel_steering_axle_idx_wheel_idx Grp_Wheel_Steering_<axle_idx>_<wheel_idx>]]
      |_ [[../geometry/object-classes.html#_grp_wheel_steering_rotating_axle_idx_wheel_idx Grp_Wheel_Steering_Rotating_<axle_idx>_<wheel_idx>]]
  |_ [[../geometry/object-classes.html#_grp_exterior_static Grp_Exterior_Static]]
|_ [[../geometry/object-classes.html#_grp_interior Grp_Interior]]
  |_ [[../geometry/object-classes.html#_grp_interior_dynamic Grp_Interior_Dynamic]]
    |_ [[../geometry/object-classes.html#_grp_eyepoint_eyepoint_idx Grp_Eyepoint_<eyepoint_idx>]]
    |_ [[../geometry/object-classes.html#_grp_mirror_rearview_mounting_rearview_mirror_mounting_idx Grp_Mirror_Rearview_Mounting_<rearview_mirror_mounting_idx>]]
      |_ [[../geometry/object-classes.html#_grp_mirror_rearview_joint_rearview_mirror_joint_idx Grp_Mirror_Rearview_Joint_<rearview_mirror_joint_idx>]]
        |_ [[../geometry/object-classes.html#_grp_mirror_rearview_view_rearview_mirror_view_idx Grp_Mirror_Rearview_View_<rearview_mirror_view_idx>]]
    |_ [[../geometry/object-classes.html#_grp_seat_seat_idx Grp_Seat_<seat_idx>]]
    |_ [[../geometry/object-classes.html#_grp_steering_wheel Grp_Steering_Wheel]]
  |_ [[../geometry/object-classes.html#_grp_interior_static Grp_Interior_Static]]
|_ [[../geometry/object-classes.html#_grp_vehicle_part Optional Grp_Vehicle_Part]]
end legend
----


== Grp_Exterior

This group contains all elements of the exterior of the vehicle.

This group typically does not move in the simulation and therefore does not have its own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Exterior_Dynamic

This group contains all dynamic elements of the exterior of the vehicle.
Dynamic elements are geometry structures which position and orientation relative to the origin on the vehicle might change throughout a simulation.
They may also change their state during the simulation, therefore lights are considered dynamic.

This group typically does not move in the simulation and therefore does not have its own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Convertible_Top

This group contains all parts of a convertible top of the vehicle.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Door_Bottom_<door_bottom_idx>

The group contains all components of a door on the bottom of the vehicle.
This also includes the interior parts of the door, since they are moved as one unit.

The `<door_bottom_idx>` is the index for all doors on the bottom counting from front to rear, starting with 0.

NOTE: Add a figure with a hatch on the bottom.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis
|===

== Grp_Door_Front_<door_front_idx>

The group contains all components of a door in the front of the vehicle.
This includes e.g. the engine cover.
This also includes the interior parts of the door, since they are moved as one unit.

The `<door_front_idx>` is the index for all doors in the front counting from right to left (in positive y direction), starting with 0.

image::Grp_Door_Front.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing towards the door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis
|===


== Grp_Door_Left_<door_left_idx>

The group contains all components of a door on the left side of the vehicle.
This also includes the interior parts of the door, since they are moved as one unit.

The `<door_left_idx>` is the index for all doors on the left counting from front to rear, starting with 0.

image::Grp_Door_Left[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing towards the door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis
|===

== Grp_Door_Rear_<door_rear_idx>

The group contains all components of a door in the rear of the vehicle.
This includes e.g. the trunklid.
This also includes the interior parts of the door, since they are moved as one unit.

The `<door_rear_idx>` is the index for all doors in the rear counting from right to left (in positive y direction), starting with 0.

image::Grp_Door_Rear.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing towards the door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis
|===


== Grp_Door_Right_<door_right_idx>

The group contains all components of a door on the right side of the vehicle.
This also includes the interior parts of the door, since they are moved as one unit.

The `<door_right_idx>` is the index for all doors on the right counting from front to rear, starting with 0.

image::Grp_Door_Right[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing towards the door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis
|===




== Grp_Door_Top_<door_top_idx>

The group contains all components of a door on the top of the vehicle.
This also includes the interior parts of the door, since they are moved as one unit.

The `<door_top_idx>` is the index for all doors on the top counting from front to rear, starting with 0.

image::Grp_Door_Top.svg[, 1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the virtual hinge axis

| *x-axis*
| Perpendicular to the z-axis, pointing towards the door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Concentric and coaxial to the virtual hinge axis
|===

== Grp_License_Plate_<license_plate_idx>

This group contains all parts of a license plate of the vehicle.

The `<license_plate_idx>` is the index for all license plates counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the plate

| *x-axis*
| Pointing outwards from the front of the plate

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Light_Brake_Center_<brake_center_idx>

This group contains all parts of a brake light in the center of the vehicle.

The `<brake_center_idx>` is the index for all brake lights in the center counting from right to left (in positive y direction), starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Light_Brake_Left_<brake_left_idx>

This group contains all parts of a brake light on the left side of the vehicle.

The `<brake_left_idx>` is the index for all brake lights on the left counting from right to left (in positive y direction), starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===



== Grp_Light_Brake_Right_<brake_right_idx>

This group contains all parts of a brake light on the right side of the vehicle.

The `<brake_right_idx>` is the index for all brake lights on the right counting from right to left (in positive y direction), starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Corner_Left_<corner_left_idx>

This group contains all parts of a corner light on the left side of the vehicle.
A corner light is a typically white light for lateral illumination in the direction of an intended turn or lane change.

The `<corner_left_idx>` is the index for all corner lights on the left counting from right to left (in positive y direction), starting with 0.

image::Grp_Light_Day_Left.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission in neutral position

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Corner_Right_<corner_right_idx>

This group contains all parts of a corner light on the right side of the vehicle.
A corner light is a typically white light for lateral illumination in the direction of an intended turn or lane change.

The `<corner_right_idx>` is the index for all corner lights on the right counting from right to left (in positive y direction), starting with 0.

image::Grp_Light_Day_Right.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission in neutral position

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===




== Grp_Light_Day_Left_<day_left_idx>

This group contains all parts of a daytime running light on the left side of the vehicle.

The `<day_left_idx>` is the index for all daytime running lights on the left counting from right to left (in positive y direction), starting with 0.

//NOTE: Add a figure. This figure might ba applicable to all lights on the front left. I don't think we have to distinguish in the figures between the different kinds of lights.
image::Grp_Light_Day_Left.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Day_Right_<day_right_idx>

This group contains all parts of a daytime running light on the right side of the vehicle.

The `<day_left_idx>` is the index for all daytime running lights on the right counting from right to left (in positive y direction), starting with 0.

//NOTE: Add a figure. This figure might be applicable to all lights on the front right. I don't think we have to distinguish in the figures between the different kinds of lights.
image::Grp_Light_Day_Right.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Fog_Left_<fog_left_idx>

This group contains all parts of a fog light on the left side of the vehicle.

The `<fog_left_idx>` is the index for all fog lights on the left counting from right to left (in positive y direction), starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Fog_Right_<fog_right_idx>

This group contains all parts of a fog light on the right side of the vehicle.

The `<fog_right_idx>` is the index for all fog lights on the right counting from right to left (in positive y direction), starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Light_High_Beam_Left_<high_beam_left_idx>

This group contains all parts of a high beam light on the left side of the vehicle.

The `<high_beam_left_idx>` is the index for all high beam lights on the left counting from right to left (in positive y direction), starting with 0.

image::Grp_Light_Day_Left.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_High_Beam_Right_<high_beam_right_idx>

This group contains all parts of a high beam light on the right side of the vehicle.

The `<high_beam_right_idx>` is the index for all high beam lights on the right counting from right to left (in positive y direction), starting with 0.

image::Grp_Light_Day_Right.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Indicator_Left_<indicator_left_idx>

This group contains all parts of an indicator light on the left side of the vehicle.

The `<indicator_left_idx>` is the index for all indicator lights on the left counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Indicator_Right_<indicator_right_idx>

This group contains all parts of an indicator light on the left side of the vehicle.

The `<indicator_right_idx>` is the index for all indicator lights on the right counting from right to left (in positive y direction), and from the front to the rear, starting with 0.


.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Light_License_Plate_<license_plate_light_idx>

This group contains all parts of a license plate light of the vehicle.

The `<license_plate_light_idx>` is the index for all license plate lights counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure for the exemplary license plate light on the rear of the vehicle.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===




== Grp_Light_Low_Beam_Left_<low_beam_left_idx>

This group contains all parts of a low beam light on the left side of the vehicle.

The `<low_beam_left_idx>` is the index for all low beam lights on the left counting from right to left (in positive y direction), starting with 0.

image::Grp_Light_Day_Left.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Low_Beam_Right_<low_beam_right_idx>

This group contains all parts of a low beam light on the right side of the vehicle.

The `<low_beam_right_idx>` is the index for all low beam lights on the right counting from right to left (in positive y direction), starting with 0.

image::Grp_Light_Day_Right.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Park_Left_<park_left_idx>

This group contains all parts of a parking light on the left side of the vehicle.

The `<park_left_idx>` is the index for all parking lights on the left counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Park_Right_<park_right_idx>

This group contains all parts of a parking light on the right side of the vehicle.

The `<park_right_idx>` is the index for all parking lights on the right counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===





== Grp_Light_Position_Left_<position_left_idx>

This group contains all parts of a position light on the left side of the vehicle.
Position lights are typically smaller, low-intensity, orange lights.

The `<position_left_idx>` is the index for all position lights on the left counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Position_Right_<position_right_idx>

This group contains all parts of a position light on the right side of the vehicle.
Position lights are typically smaller, low-intensity, orange lights.

The `<position_right_idx>` is the index for all position lights on the right counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Light_Reverse_Left_<reverse_left_idx>

This group contains all parts of a reverse light on the left side of the vehicle.

The `<reverse_left_idx>` is the index for all reverse lights on the left counting from right to left (in positive y direction), starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Reverse_Right_<reverse_right_idx>

This group contains all parts of a reverse light on the right side of the vehicle.

The `<reverse_right_idx>` is the index for all reverse lights on the right counting from right to left (in positive y direction), starting with 0.

NOTE: Add figure from tail light.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===





== Grp_Light_Tail_Left_<tail_left_idx>

This group contains all parts of a tail light on the left side of the vehicle.

The `<tail_left_idx>` is the index for all tail lights on the left counting from right to left (in positive y direction), starting with 0.

NOTE: Add a figure. This figure might be applicable to all lights on the rear left. I don't think we have to distinguish in the figures between the different kinds of lights.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Tail_Right_<tail_right_idx>

This group contains all parts of a tail light on the right side of the vehicle.

The `<tail_right_idx>` is the index for all tail lights on the right counting from right to left (in positive y direction), starting with 0.

NOTE: Add a figure. This figure might be applicable to all lights on the rear right. I don't think we have to distinguish in the figures between the different kinds of lights.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, usually backwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Light_Warning_<warning_idx>

This group contains all parts of a warning light of the vehicle.
Warning lights can be all kinds of emergency lights, hazard lights, etc.

The `<warning_idx>` is the index for all warning lights counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure on an exemplary rotating warning light on the roof the vehicle.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the light element

| *x-axis*
| Pointing towards the main light emission, or forwards for rotating lights

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Blindspot_Joint_Left_<blindspot_mirror_joint_idx> 

This group contains all parts of the main part a blindspot mirror that moves, when it is adjusted.
It is a child of the corresponding mirror mounting.

The `<blindspot_mirror_joint_idx>` is the index for all blindspot mirror joints counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Joint of the movable part of a mirror

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Blindspot_Mounting_<blindspot_mirror_mounting_idx>

This group contains all parts of a blindspot mirror mounting of the vehicle.
It shall either be a child of the Grp_Exterior_Dynamic, if mounted directly to the vehicle body, or it shall be a child of a side door, if mounted on the door.

The `<blindspot_mirror_mounting_idx>` is the index for all blindspot mountings counting from right to left (in positive y direction), and from the front to the rear, starting with 0.
The index is used consistently, whether the mirror is mounted on the door or the vehicle body.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Base of the mirror mounting

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Blindspot_View_<blindspot_mirror_view_idx>

This group is an empty node indicating the view direction of the mirror glass of a blindspot mirror.
It is a child of the corresponding mirror joint.

The `<blindspot_mirror_view_idx>` is the index for all blindspot mirrors counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the mirror glass surface

| *x-axis*
| Pointing outwards from the mirror glass, aligned with the surface normal

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards along the face of the mirror glass
|===


== Grp_Mirror_Side_Joint_Left_<side_mirror_joint_left_idx> 

This group contains all parts of the main part a mirror that moves, when it is adjusted, on the left side of the vehicle.
It is a child of the corresponding mirror mounting.

The `<side_mirror_joint_left_idx>` is the index for all mirror joint on the left counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Joint of the movable part of a mirror

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Side_Joint_Right_<side_mirror_joint_right_idx> 

This group contains all parts of the main part a mirror that moves, when it is adjusted, on the right side of the vehicle.
It is a child of the corresponding mirror mounting.

The `<side_mirror_joint_right_idx>` is the index for all mirror joint on the right counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Joint of the movable part of a mirror

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Side_Mounting_Left_<side_mirror_mounting_left_idx> 

This group contains all parts of a side mirror on the left side of the vehicle.
It shall either be a child of the Grp_Exterior_Dynamic, if mounted directly to the vehicle body, or it shall be a child of a side door, if mounted on the door.

The `<side_mirror_mounting_left_idx>` is the index for all mirror mountings on the left counting from right to left (in positive y direction), and from the front to the rear, starting with 0.
The index is used consistently, whether the mirror is mounted on the door or the vehicle body.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Base of the mirror mounting

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Side_Mounting_Right_<side_mirror_mounting_right_idx>

This group contains all parts of a mirror on the right side of the vehicle.
It shall either be a child of the Grp_Exterior_Dynamic, if mounted directly to the vehicle body, or it shall be a child of a side door, if mounted on the door.

The `<side_mirror_mounting_right_idx>` is the index for all mirror mountings on the right counting from right to left (in positive y direction), and from the front to the rear, starting with 0.
The index is used consistently, whether the mirror is mounted on the door or the vehicle body.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Base of the mirror mounting

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Side_View_Left_<side_mirror_view_left_idx>

This group is an empty node indicating the view direction of the mirror glass of a side mirror on the left side of the vehicle.
It is a child of the corresponding mirror joint.

The `<side_mirror_view_left_idx>` is the index for all mirrors on the left counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the mirror glass surface

| *x-axis*
| Pointing outwards from the mirror glass, aligned with the surface normal

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards along the face of the mirror glass
|===


== Grp_Mirror_Side_View_Right_<side_mirror_view_right_idx>

This group is an empty node indicating the view direction of the mirror glass of a side mirror on the right side of the vehicle.
It is a child of the corresponding mirror joint.

The `<side_mirror_view_right_idx>` is the index for all mirrors on the right counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the mirror glass surface

| *x-axis*
| Pointing outwards from the mirror glass, aligned with the surface normal

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards along the face of the mirror glass
|===


== Grp_Sensor_<sensor_idx>

This group contains all parts of a perception sensor of the vehicle.
The geometry of a sensor can alternatively be placed in the Grp_Exterior_Static.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the sensor

| *x-axis*
| Pointing outwards from the sensor in the direction of its longitudinal axis

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing upwards in sensor coordinates
|===

== Grp_Wheel_<axle_idx>_<wheel_idx>

This group contains all geometries of one wheel assembly.
This may include tire, rim, brake caliper etc.

The `<axle_idx>` denotes the index of the axle the wheel is mounted to, counting from the front to the rear, starting with 0.
The `<wheel_idx>` denotes the index of the wheel on the specified axle, counting from right to left (in positive y direction), starting with 0.
Example: The wheel on the front left of a standard vehicle would be `Grp_Wheel_0_1`.

Steering of the wheel is implemented by a rotation around the z-axis.
Wheel camber is defined by a rotation around the x-axis.
Suspension deflection is represented by a translation along the z-axis.
Zero rotation and and translation around all axles are defined in neutral load conditions.
In the 3D model, both caster and camber angles are neglected.

image::Grp_Wheel.svg[,1100]

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the wheel

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Wheel_Steering_<axle_idx>_<wheel_idx>

This group contains all components of the wheel assembly, that follow the steering motion but not the rotation of the wheel, e.g. brake calipers.

The indices are the same as in the parent group.

This group typically does not move independently in the simulation as it moves with the parent transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the wheel

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Wheel_Steering_Rotating_<axle_idx>_<wheel_idx>

This group contains all components of the wheel assembly, that follow the steering motion as well as the rotation of the wheel, e.g. tire and rim.

The indices are the same as in the parent group.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Geometric center of the wheel

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing towards the door

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Exterior_Static

This group contains all static elements of the exterior of the vehicle.
Static elements are geometry structures that have a fixed position and orientation relative to the origin on the vehicle throughout a simulation.
They also do not change their state during the simulation, therefore lights are considered dynamic.

This group typically does not move in the simulation and therefore does not have its own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Interior

This group contains all elements of the interior of the vehicle.
The interior is separated form the exterior to enable disabling or exchanging it in the simulation.

This group typically does not move in the simulation and therefore does not have its own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Interior_Dynamic

This group contains all dynamic elements of the exterior of the vehicle.
Dynamic elements are geometry structures which position and orientation relative to the origin on the vehicle might change throughout a simulation.
They may also change their state during the simulation, therefore lights are considered dynamic.

This group typically does not move in the simulation and therefore does not have its own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Eyepoint_<eyepoint_idx>

This group contains is an empty element containing the origin of an average passenger of the vehicle.

The `<eyepoint_idx>` is the index for all eye points counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the eye view point

| *x-axis*
| Collinear with the view direction

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards in neutral position
|===


== Grp_Mirror_Rearview_Joint_Left_<rearview_mirror_joint_idx> 

This group contains all parts of the main part a rearview mirror that moves, when it is adjusted.
It is a child of the corresponding mirror mounting.

The `<rearview_mirror_joint_idx>` is the index for all rearview mirror joints counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Joint of the movable part of a mirror

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Rearview_Mounting_<rearview_mirror_mounting_idx>

This group contains all parts of a rearview mirror mounting of the vehicle.

The `<rearview_mirror_mounting_idx>` is the index for all rearview mirrors mounting counting from right to left (in positive y direction), and from the front to the rear, starting with 0.
The index is used consistently, whether the mirror is mounted on the door or the vehicle body.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Base of the mirror mounting

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Mirror_Rearview_View_<rearview_mirror_view_idx>

This group is an empty node indicating the view direction of the mirror glass of a rearview mirror.
It is a child of the corresponding mirror joint.

The `<rearview_mirror_view_idx>` is the index for all rearview mirrors counting from right to left (in positive y direction), and from the front to the rear, starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the mirror glass surface

| *x-axis*
| Pointing outwards from the mirror glass, aligned with the surface normal

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards along the face of the mirror glass
|===


== Grp_Seat_<seat_idx>

This group contains all parts of a seat of the vehicle.

The seat position can be used for the placement of a human 3D model as a passenger.
Therefore, a bench is consists of multiple individual seats.

The `<seat_idx>` is the index for all seats counting from from the front to the rear and right to left (in positive y direction), starting with 0.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the seat cushion.

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing in the direction of the seat

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===

== Grp_Steering_Wheel

This group contains all elements of the steering wheel of the vehicle.

NOTE: Add a figure.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the steering wheel

| *x-axis*
| Collinear with the steering column, pointing towards the axis

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards in neutral position
|===


== Grp_Interior_Static

This group contains all static elements of the interior of the vehicle.
Static elements are geometry structures that have a fixed position and orientation relative to the origin on the vehicle throughout a simulation.
They also do not change their state during the simulation, therefore lights are considered dynamic.

This group typically does not move in the simulation and therefore does not have its own transforms.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Origin of the vehicle

| *x-axis*
| Collinear with the vehicle longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===


== Grp_Vehicle_Part

One or multiple optional vehicle parts may be added to the main vehicle structure.
A vehicle part is a large structure of the vehicle, that moves based on other parts of the same vehicle.
A vehicle may have multiple vehicle parts on the same hierarchy level or in a parent-child relationship.
This mainly applies to articulated vehicles, e.g. a front loader with a hinged axis or an articulated bus with a hinge in the middle.
It may also apply to construction vehicles.
When a vehicle part can be detached, like a trailer, it is to be treated as a separate object and not a vehicle part.

The child nodes of a vehicle part may follow the same node structure as the main vehicle, e.g. if a vehicle parts has lights, they may use the same structure and naming conventions as the main vehicle.

Standard passenger vehicles do not have separate parts.

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| Center of the joint to the main vehicle or the parent.

| *x-axis*
| Collinear with the parts longitudinal axis, pointing forwards

| *y-axis*
| Completes the right-handed coordinate system

| *z-axis*
| Perpendicular to the x-axis, pointing vertically upwards
|===