= Grp_Vehicle_Part_keyword_vehicle_part_idx (T)

Add a description

.<Table title>
[%header, cols="20, 80"]
|===

2+^| <Header>

| *Origin*
| ...

| *x-axis*
| ...

| *y-axis*
| ...

| *z-axis*
| ...
|===


Add a figure.

.<Figure caption>
//image::images/Vehicle_Structure_Door_Coord_Frame.svg[width=70%, scalewidth=10cm]

////
General note: Grp_* Nodes are empty nodes  
////
////
The structure can be extended by custom groups for additional use-cases. Custom groups shall follow the general structure (e.g. grouping into static/dynamic, interior/exterior).

Each vehicle part has its own transform .

Vehicle Parts are for moving entire parts of the vehicle, e.g. in a hinged bus or construction vehicle with a hinge (articulated vehicles). When a vehicle part can be detached, like a trailer, it is to be treated as a separate vehicle and not a vehicle part. 
Comment LF: Trailers and train wagons are treated as separate vehicles

Comment MT: MT: What about buses with middle axis? More complex geometries/functions? Multiple Trailers? movable Cabins?  
Should add nodes for trailer coupling devices, so that you know where to attach (MT)  

////
