= Introduction

In {THIS_STANDARD}, an object class is a collection of similar objects.
Examples of object classes are vehicles, humans, and road networks.
Each instance of an object class is described by the same properties but has
individual property values.

The {THIS_STANDARD} standard supports the following object classes:

* xref:../07_geometry/object-vehicle/vehicle-index.adoc[Vehicle]
* xref:../07_geometry/object-human/human-index.adoc[Human]
* xref:../07_geometry/object-environment/environment-index.adoc[Environment]
* xref:../07_geometry/object-other/other-index.adoc[Other]

If a human is clearly distinguishable from a vehicle, then both the
human and the vehicle are represented by two different objects respectively. Examples are
bicycles, motorbikes, or scooters, where the human and the vehicle are
perceived as separate entities.

The other object class comprises all objects not yet specified by {THIS_STANDARD}.
It includes all objects that are not specified by type-specific object classes.
Definitions in type-specific object classes overwrite the specifications in the other object class.