[#top-preface-foreword]
= Foreword

ifndef::include-only-once[]
:root-path: ../
include::{root-path}_config.adoc[]
endif::[]

ASAM e.V. (Association for Standardization of Automation and Measuring Systems) is a non-profit organization that promotes standardization of tool chains in automotive development and testing.
Our members are international car manufacturers, suppliers, tool vendors, engineering service providers, and research institutes.
ASAM standards are developed by experts from our member companies and are based on real use cases.
ASAM is the legal owner of these standards and is responsible for their distribution and marketing.

ASAM standards span a wide range of use cases in automotive development, test, and validation.
They define file formats, data models, protocols, and interfaces.
The standards enable easy exchange of data and tools within and across tool chains.
They are applied worldwide.

{THIS_STANDARD} defines physical material properties and standardizes 3D model structures addressing the need for accurate, standardized 3D assets and material properties to simulate sensor behavior effectively.

{THIS_STANDARD} is divided into two key chapters:

- Material: Covers formats and definitions for material properties, such as surface roughness and reflectance data.
- Geometry: Establishes structures for object classes, standardizing nodes, naming, and coordinate systems to support 3D model exchange and animation.
