= Model structure

== Structure overview

[plantuml]
----
legend
|_ [[../geometry/object-classes.html#_grp_root Grp_Root]]
  |_ [[../geometry/object-classes.html#_skeleton Skeleton]]
    |_ [[../geometry/object-classes.html#_root Root]]
      |_ [[../geometry/object-classes.html#_hip Hip]]
        |_ [[../geometry/object-classes.html#_lower_spine Lower_Spine]]
          |_ [[../geometry/object-classes.html#_upper_spine Upper_Spine]]
            |_ [[../geometry/object-classes.html#_neck Neck]]
              |_ [[../geometry/object-classes.html#_head Head]]
                |_ [[../geometry/object-classes.html#_eye_left Eye_Left]]
                |_ [[../geometry/object-classes.html#_eye_right Eye_Right]]
          |_ [[../geometry/object-classes.html#_shoulder_left Shoulder_Left]]
            |_ [[../geometry/object-classes.html#_upper_arm_left Upper_Arm_Left]]
              |_ [[../geometry/object-classes.html#_lower_arm_left Lower_Arm_Left]]
                |_ [[../geometry/object-classes.html#_hand_left Hand_Left]]
                  |_ [[../geometry/object-classes.html#_full_lingers_left Full_Fingers_Left]]
                  |_ [[../geometry/object-classes.html#_full_thumb_left Full_Thumb_Left]]
            |_ [[../geometry/object-classes.html#_upper_arm_right Upper_Arm_Right]]
              |_ [[../geometry/object-classes.html#_lower_arm_right Lower_Arm_Right]]
                |_ [[../geometry/object-classes.html#_hand_right Hand_Right]]
                  |_ [[../geometry/object-classes.html#_full_fingers_right Full_Fingers_Right]]
                  |_ [[../geometry/object-classes.html#_full_thumb_right Full_Thumb_Right]]
      |_ [[../geometry/object-classes.html#_upper_leg_left Upper_Leg_Left]]
        |_ [[../geometry/object-classes.html#_lower_leg_left Lower_Leg_Left]]
          |_ [[../geometry/object-classes.html#_foot_left Foot_Left]]
            |_ [[../geometry/object-classes.html#_full_toes_left Full_Toes_Left]]
      |_ [[../geometry/object-classes.html#_upper_leg_right Upper_Leg_Right]]
        |_ [[../geometry/object-classes.html#_lower_leg_right Lower_Leg_Right]]
          |_ [[../geometry/object-classes.html#_foot_right Foot_Right]]
            |_ [[../geometry/object-classes.html#_full_toes_right Full_Toes_Right]]
  |_ [[../geometry/object-classes.html#_accessories Accessories_Wristband]]
  |_ [[../geometry/object-classes.html#_body Body_Human]]
  |_ [[../geometry/object-classes.html#_clothing Clothing_Vest]]
  |_ [[../geometry/object-classes.html#_hair Hair_Short]]
end legend
----

== Grp_Root 

This group is used as a parent for all following nodes. It can be used to place the whole asset and select the complete node hierarchy at once. The transformation is set to 0 for all axes.

.Grp_Root 
[%header, cols="20, 80"]
|===

2+^| Grp_Root

| *Origin*
| Center of the bounding box on the ground

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing sidewards

| *z-axis*
| Pointing upwards
|===


== Accessories_<Name>

This object represents an additional or exchangeable accessory of the human.

.Accessories 
[%header, cols="20, 80"]
|===

2+^| Accessories

| *Origin*
| Center of the bounding box on the ground

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing sidewards

| *z-axis*
| Pointing upwards

|===


== Body_<Name>

This object represents the body of the human.

.Body
[%header, cols="20, 80"]
|===

2+^| Body

| *Origin*
| Center of the bounding box on the ground

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing sidewards

| *z-axis*
| Pointing upwards
|===


== Clothing_<Name>

This object represents an additional or exchangeable clothing part of the human.

.Clothing
[%header, cols="20, 80"]
|===

2+^| Clothing

| *Origin*
| Center of the bounding box on the ground

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing sidewards

| *z-axis*
| Pointing upwards
|===


== Hair_<Name>

This object represents an additional or exchangeable hair part of the human.

.Hair
[%header, cols="20, 80"]
|===

2+^| Hair

| *Origin*
| Center of the bounding box on the ground

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing sidewards

| *z-axis*
| Pointing upwards
|===


== Root

The `Root` bone is the parent bone for all other bones. It can be used to control the whole skeleton.

.Root bone
[%header, cols="20, 80"]
|===

2+^| Root

| *Origin*
| World coordinate system

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Hip

The `Hip` bone represents the lowest parts and bones of the spine, that is, the Hip, Coccyx and Sacrum spine bones of the human skeleton.

.Hip bone
[%header, cols="20, 80"]
|===

2+^| Hip

| *Origin*
| At the height of the Coccyx bone and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Lower_Spine

The `Lower_Spine` bone represents the middle parts und bones of the spine, that is, the Lumbar spine bones of the human skeleton.

.Lower_Spine bone
[%header, cols="20, 80"]
|===

2+^| Lower_Spine

| *Origin*
| At the height of the first Lumbar spine bone and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Upper_Spine 

The `Upper_Spine` bone represents the upper parts und bones of the spine, that is, the Thoracic spine bones of the human skeleton.

.Upper_Spine bone
[%header, cols="20, 80"]
|===

2+^| Upper_Spine

| *Origin*
| At the height of the lowest Thoracic spine bone and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Neck 

The `Neck` bone represents the most upper parts und bones of the spine, that is, the Cervical spine bones of the human skeleton.

.Neck bone
[%header, cols="20, 80"]
|===

2+^| Neck 

| *Origin*
| At the height of the lowest Cervical spine bone and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Head

The `Head` bone represents the head, that is, the skull of the human skeleton.

.Head bone
[%header, cols="20, 80"]
|===

2+^| Head

| *Origin*
| At the height of the first Cervical spine bone and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Eye_Left

The `Eye_Left` bone represents the left eye of the human body. It is used to calculate the eye level.

.Eye_Left bone
[%header, cols="20, 80"]
|===

2+^| Eye_Left

| *Origin*
| At the middle of the (eyeball) geometry

| *x-axis*
| Pointing upwards

| *y-axis*
| Pointing forwards

| *z-axis*
| Pointing sidewards
|===


== Eye_Right

The `Eye_Right` bone represents the right eye of the human body. It is used to calculate the eye level.

.Eye_Right bone
[%header, cols="20, 80"]
|===

2+^| Eye_Right

| *Origin*
| At the middle of the (eyeball) geometry

| *x-axis*
| Pointing upwards

| *y-axis*
| Pointing forwards

| *z-axis*
| Pointing sidewards
|===


== Shoulder_Left 

The `Shoulder_Left` bone represents the upper part of the left shoulder, that is, the interaction between the clavicle bone and the humerus head of the human skeleton.

.Shoulder_Left bone
[%header, cols="20, 80"]
|===

2+^| Shoulder_Left

| *Origin*
| At the height of the clavicle bone and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Upper_Arm_Left

The `Upper_Arm_Left` bone represents the upper part of the left arm, that is, the humerus head of the human skeleton.

.Upper_Arm_Left bone
[%header, cols="20, 80"]
|===

2+^| Upper_Arm_Left

| *Origin*
| At the height of the humerus head and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Lower_Arm_Left

The `Lower_Arm_Left` bone represents the lower part of the left arm, that is, the left elbow and Radius and Ulna of the human skeleton.

.Lower_Arm_Left bone
[%header, cols="20, 80"]
|===

2+^| Lower_Arm_Left

| *Origin*
| At the height of the elbow and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Hand_Left

The `Hand_Left` bone represents the left hand, that is, the left carpal bones of the human skeleton.

.Hand_Left bone
[%header, cols="20, 80"]
|===

2+^| Hand_Left

| *Origin*
| At the height of the beginning carpal bones and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Full_Thumb_Left 

The `Full_Thumb_Left` bone represents the thumb of the left hand, that is, the full thumb of the human skeleton.

.Full_Thumb_Left bone
[%header, cols="20, 80"]
|===

2+^| Full_Thumb_Left

| *Origin*
| At the height of the beginning carpal bones and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Full_Fingers_Left

The `Full_Fingers_Left` bone represents all other fingers of the left hand, that is, the full index finger, middle finger, ring finger, and pinkie finger of the human skeleton. The middle finger position and length are used to place the bone correctly.

.Full_Fingers_Left bone
[%header, cols="20, 80"]
|===

2+^| Full_Fingers_Left

| *Origin*
| At the height of the beginning carpal bones and in the middle of the hand geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Shoulder_Right 

The `Shoulder_Right` bone represents the upper part of the right shoulder, that is, the interaction between the clavicle bone and the humerus head of the human skeleton.

.Shoulder_Right bone
[%header, cols="20, 80"]
|===

2+^| Shoulder_Right

| *Origin*
| At the height of the clavicle bone and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Upper_Arm_Right

The `Upper_Arm_Right` bone represents the upper part of the right arm, that is, the humerus head of the human skeleton.

.Upper_Arm_Right bone
[%header, cols="20, 80"]
|===

2+^| Upper_Arm_Right

| *Origin*
| At the height of the humerus head and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Lower_Arm_Right

The `Lower_Arm_Right` bone represents the lower part of the right arm, that is, the right elbow and Radius and Ulna of the human skeleton.

.Lower_Arm_Right bone
[%header, cols="20, 80"]
|===

2+^| Lower_Arm_Right

| *Origin*
| At the height of the elbow and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Hand_Right

The `Hand_Right` bone represents the right hand, that is, the right carpal bones of the human skeleton.

.Hand_Right bone
[%header, cols="20, 80"]
|===

2+^| Hand_Right

| *Origin*
| At the height of the beginning carpal bones and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Full_Thumb_Right

The `Full_Thumb_Right` bone represents the thumb of the right hand, that is, the full thumb of the human skeleton.

.Full_Thumb_Right bone
[%header, cols="20, 80"]
|===

2+^| Full_Thumb_Right

| *Origin*
| At the height of the beginning carpal bones and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Full_Fingers_Right

The `Full_Fingers_Right` bone represents all other fingers of the right hand, that is, the full index finger, middle finger, ring finger, and pinkie finger. The middle finger position and length are used to place the bone correctly.

.Full_Fingers_Right bone
[%header, cols="20, 80"]
|===

2+^| Full_Fingers_Right

| *Origin*
| At the height of the beginning carpal bones and in the middle of the hand geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


The `Upper_Leg_Left` bone represents the upper part of the left leg, that is, the thigh of the human skeleton. It controls the hip joint.

.Upper_Leg_Left bone
[%header, cols="20, 80"]
|===

2+^| Upper_Leg_Left

| *Origin*
| At the height of the hip joint and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Lower_Leg_Left

The `Lower_Leg_Left` bone represents the lower part of the left leg, that is, the Tibula and Fibula of the human skeleton. It controls the knee.

.Lower_Leg_Left bone
[%header, cols="20, 80"]
|===

2+^| Lower_Leg_Left

| *Origin*
| At the height of the knee and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Foot_Left 

The `Foot_Left` bone represents the left foot of the human skeleton without the toes. It controls the ankle.

.Foot_Left bone
[%header, cols="20, 80"]
|===

2+^| Foot_Left

| *Origin*
| At the height of the ankle and in the middle of the geometry

| *x-axis*
| Pointing upwards

| *y-axis*
| Pointing forwards

| *z-axis*
| Pointing sidewards
|===


== Full_Toes_Left 

The `Full_Toes_Left` bone represents all toes of the left foot of the human skeleton.

.Full_Toes_Left bone
[%header, cols="20, 80"]
|===

2+^| Full_Toes_Left 

| *Origin*
| At the height of the phalanges and in the middle of the geometry

| *x-axis*
| Pointing upwards

| *y-axis*
| Pointing forwards

| *z-axis*
| Pointing sidewards
|===


== Upper_Leg_Right

The `Upper_Leg_Right` bone represents the upper part of the right leg, that is, the thigh of the human skeleton. It controls the hip joint.

.Upper_Leg_Right bone
[%header, cols="20, 80"]
|===

2+^| Upper_Leg_Right

| *Origin*
| At the height of the hip joint and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Lower_Leg_Right

The `Lower_Leg_Right` bone represents the lower part of the right leg, that is, the Tibula and Fibula of the human skeleton. It controls the knee.

.Lower_Leg_Right bone
[%header, cols="20, 80"]
|===

2+^| Lower_Leg_Right

| *Origin*
| At the height of the knee and in the middle of the geometry

| *x-axis*
| Pointing forwards

| *y-axis*
| Pointing upwards

| *z-axis*
| Pointing sidewards
|===


== Foot_Right

The `Foot_Right` bone represents the right foot of the human skeleton without the toes. It controls the ankle.

.Foot_Right bone
[%header, cols="20, 80"]
|===

2+^| Foot_Right

| *Origin*
| At the height of the ankle and in the middle of the geometry

| *x-axis*
| Pointing upwards

| *y-axis*
| Pointing forwards

| *z-axis*
| Pointing sidewards
|===


== Full_Toes_Right

The `Full_Toes_Right` bone in a human skeleton represents all toes of the right foot of the human skeleton.

.Full_Toes_Right bone
[%header, cols="20, 80"]
|===

2+^| Full_Toes_Right 

| *Origin*
| At the height of the phalanges and in the middle of the geometry

| *x-axis*
| Pointing upwards

| *y-axis*
| Pointing forwards

| *z-axis*
| Pointing sidewards
|===

