= Model structure

== Structure overview

----
|_ [[../geometry/object-classes.html#_grp_root Grp_Root]]
  |_ [[../geometry/object-classes.html#_skeleton Skeleton]]
    |_ [[../geometry/object-classes.html#_root Root]]
      |_ [[../geometry/object-classes.html#_lower_spine Lower_Spine]]
        |_ [[../geometry/object-classes.html#_hip_left Hip_Left]]
        |_ [[../geometry/object-classes.html#_hip_right Hip_Right]]
        |_ [[../geometry/object-classes.html#_middle_spine Middle_Spine]]
          |_ [[../geometry/object-classes.html#_upper_spine Upper_Spine]]
            |_ [[../geometry/object-classes.html#_neck Neck]]
              |_ [[../geometry/object-classes.html#_head Head]]
                |_ [[../geometry/object-classes.html#_eye_left Eye_Left]]
                |_ [[../geometry/object-classes.html#_eye_right Eye_Right]]
          |_ [[../geometry/object-classes.html#_shoulder_left Shoulder_Left]]
            |_ [[../geometry/object-classes.html#_upper_arm_left Upper_Arm_Left]]
              |_ [[../geometry/object-classes.html#_lower_arm_left Lower_Arm_Left]]
                |_ [[../geometry/object-classes.html#_hand_left Hand_Left]]
                  |_ [[../geometry/object-classes.html#_full_lingers_left Full_Fingers_Left]]
                  |_ [[../geometry/object-classes.html#_full_thumb_left Full_Thumb_Left]]
            |_ [[../geometry/object-classes.html#_upper_arm_right Upper_Arm_Right]]
              |_ [[../geometry/object-classes.html#_lower_arm_right Lower_Arm_Right]]
                |_ [[../geometry/object-classes.html#_hand_right Hand_Right]]
                  |_ [[../geometry/object-classes.html#_full_fingers_right Full_Fingers_Right]]
                  |_ [[../geometry/object-classes.html#_full_thumb_right Full_Thumb_Right]]
      |_ [[../geometry/object-classes.html#_upper_leg_left Upper_Leg_Left]]
        |_ [[../geometry/object-classes.html#_lower_leg_left Lower_Leg_Left]]
          |_ [[../geometry/object-classes.html#_foot_left Foot_Left]]
            |_ [[../geometry/object-classes.html#_full_toes_left Full_Toes_Left]]
      |_ [[../geometry/object-classes.html#_upper_leg_right Upper_Leg_Right]]
        |_ [[../geometry/object-classes.html#_lower_leg_right Lower_Leg_Right]]
          |_ [[../geometry/object-classes.html#_foot_right Foot_Right]]
            |_ [[../geometry/object-classes.html#_full_toes_right Full_Toes_Right]]
  |_ [[../geometry/object-classes.html#_grp_accessories Grp_Accessories]]
    |_ [[../geometry/object-classes.html#_accessorie Accessorie]]
  |_ [[../geometry/object-classes.html#_grp_body Grp_Body]]
    |_ [[../geometry/object-classes.html#_human Human]]
  |_ [[../geometry/object-classes.html#_grp_clothing Grp_Clothing]]
    |_ [[../geometry/object-classes.html#_vest Vest]]
  |_ [[../geometry/object-classes.html#_grp_hair Grp_Hair]]
    |_ [[../geometry/object-classes.html#_hair Hair]]
----


== Grp_Root 

This group is used as a parent for all following nodes. It can be used to place the whole asset and select the complete node hierarchy at once.
The origin of the Root group is set at the world origin.

.Grp_Root 
[%header, cols="20, 40, 40"]
|===

3+^| Grp_Root

| *Axis*
| *World origin*
| *Direction*

| *X*
| 0
| Forward

| *Y*
| 0 
| Side

| *Z*
| 0
| Up
|===


== Grp_Accessories

This group contains all additional or exchangable accessories of the human.
The origin of the Accessories group is set at the world origin.

.Grp_Accessories 
[%header, cols="20, 40, 40"]
|===

3+^| Grp_Accessories

| *Axis*
| *World origin*
| *Direction*

| *X*
| 0
| Forward

| *Y*
| 0 
| Side

| *Z*
| 0
| Up
|===


== Grp_Body

This group contains the body of the human.
The origin of the Body group is set at the world origin.

.Grp_Body
[%header, cols="20, 40, 40"]
|===

3+^| Grp_Body

| *Axis*
| *World origin*
| *Direction*

| *X*
| 0
| Forward

| *Y*
| 0 
| Side

| *Z*
| 0
| Up
|===


== Grp_Clothing

This group contains all additional or exchangable cloth parts of the human.
The origin of the Clothing group is set at the world origin.

.Grp_Clothing
[%header, cols="20, 40, 40"]
|===

3+^| Grp_Clothing

| *Axis*
| *World origin*
| *Direction*

| *X*
| 0
| Forward

| *Y*
| 0 
| Side

| *Z*
| 0
| Up
|===


== Grp_Hair

This group contains all additional or exchangable hair parts of the human.
The origin of the Hair group is set at the world origin.

.Grp_Hair
[%header, cols="20, 40, 40"]
|===

3+^| Grp_Hair

| *Axis*
| *World origin*
| *Direction*

| *X*
| 0
| Forward

| *Y*
| 0 
| Side

| *Z*
| 0
| Up
|===


== Root

The `Root` bone is the parent bone for all other bones. It can be used to controll the whole skeleton.
The origin of the `Root` bone is set at the world origin.

.Root bone
[%header, cols="20, 40, 40"]
|===

3+^| Root

| *Axis*
| *World origin*
| *Direction*

| *X*
| 0
| Forward

| *Y*
| 0 
| Side

| *Z*
| 0
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Lower_Spine

The `Lower_Spine` bone represents the lowest parts and bones of the spine. Transferred to a human skeleton, it represents and controlls the Coccyx and Sacrum spine bones.
The origin of the `Lower_Spine` bone should be set at the height of the Coccyx bone and in the middle of the geometry.

.Lower_Spine bone
[%header, cols="20, 80"]
|===

2+^| Lower_Spine

| *Axis*
| *Direction*

| *X*
| Forward

| *Y*
| Up

| *Z*
| Side
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Middle_Spine

The `Middle_Spine` bone represents the mid parts und bones of the spine. Transferred to a human skeleton, it represents and controlls the Lumbar spine bones.
The origin of the `Middle_Spine` bone should be set at the height of the first Lumbar spine bone and in the middle of the geometry.

.Middle_Spine bone
[%header, cols="20, 80"]
|===

2+^| Middle_Spine

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]

== Upper_Spine 

The `Upper_Spine` bone represents the upper parts und bones of the spine. Transferred to a human skeleton, it represents and controlls the Thoracic spine bones.
The origin of the `Upper_Spine` bone should be set at the height of the lowest Thoracic spine bone and in the middle of the geometry.

.Upper_Spine bone
[%header, cols="20, 80"]
|===

2+^| Upper_Spine

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Neck 

The `Neck` bone represents the most upper parts und bones of the spine. Transferred to a human skeleton, it represents and controlls the Cervical spine bones.
The origin of the `Neck` bone should be set at the height of the lowest Cervical spine bone and in the middle of the geometry.

.Neck bone
[%header, cols="20, 80"]
|===

2+^| Neck 

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Head

The `Head` bone represents the head. Transferred to a human skeleton, it represents and controlls the skull.
The origin of the `Head` bone should be set at the height of the first Cervical spine bone and in the middle of the geometry.

.Head bone
[%header, cols="20, 80"]
|===

2+^| Head

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Eye_Left

The `Eye_Left` bone represents the left eye. It is used to represent the left eye and to allow the calculation of the eye level.
The origin of the `Eye_Left` bone should be set at the middle of the (eyeball) geometry.

.Eye_Left bone
[%header, cols="20, 80"]
|===

2+^| Eye_Left

| *Axis*
| Direction

| *X*
| Up

| *Y*
| Forward

| *Z*
| Side
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Eye_Right

The `Eye_Right` bone represents the left eye. It is used to represent the left eye and to allow the calculation of the eye level.
The origin of the `Eye_Right` bone should be set at the middle of the (eyeball) geometry.

.Eye_Right bone
[%header, cols="20, 80"]
|===

2+^| Eye_Right

| *Axis*
| Direction

| *X*
| Up

| *Y*
| Forward

| *Z*
| Side
|===

//Note: Please add a figure and description.
//[Image Placeholder]


== Shoulder_Left 

The `Shoulder_Left` bone represents the upper part of the left shoulder. Transferred to a human skeleton, it represents and controlls the interaction between the clavicle bone and the humerus head.
The origin of the `Shoulder_Left` bone should be set at the height of the clavicle bone and in the middle of the geometry.

.Shoulder_Left bone
[%header, cols="20, 80"]
|===

2+^| Shoulder_Left

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Upper_Arm_Left

The `Upper_Arm_Left` bone represents the upper part of the left arm. Transferred to a human skeleton, it represents and controlls the humerus head.
The origin of the `Upper_Arm_Left` bone should be set at the height of the humerus head and in the middle of the geometry.

.Upper_Arm_Left bone
[%header, cols="20, 80"]
|===

2+^| Upper_Arm_Left

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]

== Lower_Arm_Left

The `Lower_Arm_Left` bone represents the lower part of the left arm. Transferred to a human skeleton, it represents and controlls the elbow.
The origin of the `Lower_Arm_Left` bone should be set at the height of the elbow and in the middle of the geometry.

.Lower_Arm_Left bone
[%header, cols="20, 80"]
|===

2+^| Lower_Arm_Left

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]

== Hand_Left

The `Hand_Left` bone represents the left hand. Transferred to a human skeleton, it represents and controlls the carpal bones.
The origin of the `Hand_Left` bone should be set at the height of the beginning carpal bones and in the middle of the geometry.

.Hand_Left bone
[%header, cols="20, 80"]
|===

2+^| Hand_Left

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Full_Thumb_Left 

The `Full_Thumb_Left` bone represents the thumb of the left hand. Transferred to a human skeleton, it represents and controlls the full thumb.
The origin of the `Full_Thumb_Left` bone should be set at the height of the beginning carpal bones and in the middle of the geometry.

.Full_Thumb_Left bone
[%header, cols="20, 80"]
|===

2+^| Full_Thumb_Left

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Up

| *Z*
| Side
|===


//Note: Please add a figure and description.
//[Image Placeholder]

== Full_Fingers_Left

The `Full_Fingers_Left` bone represents all other fingers of the left hand. Transferred to a human skeleton, it represents and controlls the full index finger, middle finger, ring finger and pinke finger.
The origin of the `Full_Fingers_Left` bone should be set at the height of the beginning carpal bones and in the middle of the hand geometry. The middle finger position and length should be used to place the bone correctly.

.Full_Fingers_Left bone
[%header, cols="20, 80"]
|===

2+^| Full_Fingers_Left

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Up

| *Z*
| Side
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Shoulder_Right 

The `Shoulder_Right` bone represents the upper part of the right shoulder. Transferred to a human skeleton, it represents and controlls the interaction between the clavicle bone and the humerus head.
The origin of the `Shoulder_Right` bone should be set at the height of the clavicle bone and in the middle of the geometry.

.Shoulder_Right bone
[%header, cols="20, 80"]
|===

2+^| Shoulder_Right

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Upper_Arm_Right

The `Upper_Arm_Right` bone represents the upper part of the right arm. Transferred to a human skeleton, it represents and controlls the humerus head.
The origin of the `Upper_Arm_Right` bone should be set at the height of the humerus head and in the middle of the geometry.

.Upper_Arm_Righ bone
[%header, cols="20, 80"]
|===

2+^| Upper_Arm_Righ

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]

== Lower_Arm_Right

The `Lower_Arm_Right` bone represents the lower part of the right arm. Transferred to a human skeleton, it represents and controlls the elbow.
The origin of the `Lower_Arm_Right` bone should be set at the height of the elbow and in the middle of the geometry.

.Lower_Arm_Right bone
[%header, cols="20, 80"]
|===

2+^| Lower_Arm_Right

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]

== Hand_Right

The `Hand_Right` bone represents the right hand. Transferred to a human skeleton, it represents and controlls the carpal bones.
The origin of the `Hand_Right` bone should be set at the height of the beginning carpal bones and in the middle of the geometry.

.Hand_Right bone
[%header, cols="20, 80"]
|===

2+^| Hand_Right

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Full_Thumb_Right

The `Full_Thumb_Right` bone represents the thumb of the right hand. Transferred to a human skeleton, it represents and controlls the full thumb.
The origin of the `Full_Thumb_Right` bone should be set at the height of the beginning carpal bones and in the middle of the geometry.

.Full_Thumb_Right bone
[%header, cols="20, 80"]
|===

2+^| Full_Thumb_Right

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Up

| *Z*
| Side
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Full_Fingers_Right

The `Full_Fingers_Right` bone represents all other fingers of the right hand. Transferred to a human skeleton, it represents and controlls the full index finger, middle finger, ring finger and pinke finger.
The origin of the `Full_Fingers_Right` bone should be set at the height of the beginning carpal bones and in the middle of the hand geometry. The middle finger position and length should be used to place the bone correctly.

.Full_Fingers_Right bone
[%header, cols="20, 80"]
|===

2+^| Full_Fingers_Right

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Up

| *Z*
| Side
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Upper_Leg_Left

The `Upper_Leg_Left` bone represents the upper part of the left leg. Transferred to a human skeleton, it represents the tgigh and controlls the hip joint.
The origin of the `Upper_Leg_Left` bone should be set at the height of the hip joint and in the middle of the geometry.

.Upper_Leg_Left bone
[%header, cols="20, 80"]
|===

2+^| Upper_Leg_Left

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Lower_Leg_Left

The `Lower_Leg_Left` bone represents the lower part of the left leg. Transferred to a human skeleton, it represents the leg and controlls the knee.
The origin of the `Lower_Leg_Left` bone should be set at the height of the knee and in the middle of the geometry.

.Lower_Leg_Left bone
[%header, cols="20, 80"]
|===

2+^| Lower_Leg_Left

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Foot_Left 

The `Foot_Left` bone represents the left foot without the toes. Transferred to a human skeleton, it represents the foot and controlls the ankle.
The origin of the `Foot_Left` bone should be set at the height of the ankle and in the middle of the geometry.

.Foot_Left bone
[%header, cols="20, 80"]
|===

2+^| Foot_Left

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Full_Toes_Left 

The `Full_Toes_Left` bone represents the all toes of the left foot. Transferred to a human skeleton, it represents and controlls the toes.
The origin of the `Full_Toes_Left` bone should be set at the height of the phalanges and in the middle of the geometry.

.Full_Toes_Left bone
[%header, cols="20, 80"]
|===

2+^| Full_Toes_Left 

| *Axis*
| Direction

| *X*
| Up

| *Y*
| Forward

| *Z*
| Side
|===


//Note: Please add a figure and description.
//[Image Placeholder]

== Upper_Leg_Right

The `Upper_Leg_Right` bone represents the upper part of the right leg. Transferred to a human skeleton, it represents the tgigh and controlls the hip joint.
The origin of the `Upper_Leg_Right` bone should be set at the height of the hip joint and in the middle of the geometry.

.Upper_Leg_Right bone
[%header, cols="20, 80"]
|===

2+^| Upper_Leg_Right

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Lower_Leg_Right

The `Lower_Leg_Right` bone represents the lower part of the right leg. Transferred to a human skeleton, it represents the leg and controlls the knee.
The origin of the `Lower_Leg_Right` bone should be set at the height of the knee and in the middle of the geometry.

.Lower_Leg_Right bone
[%header, cols="20, 80"]
|===

2+^| Lower_Leg_Right

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Foot_Right

The `Foot_Right` bone represents the right foot without the toes. Transferred to a human skeleton, it represents the foot and controlls the ankle.
The origin of the `Foot_Right` bone should be set at the height of the ankle and in the middle of the geometry.

.Foot_Right bone
[%header, cols="20, 80"]
|===

2+^| Foot_Right

| *Axis*
| Direction

| *X*
| Forward

| *Y*
| Side

| *Z*
| Up
|===


//Note: Please add a figure and description.
//[Image Placeholder]


== Full_Toes_Right

The `Full_Toes_Right` bone represents the all toes of the right foot. Transferred to a human skeleton, it represents and controlls the toes.
The origin of the `Full_Toes_Right` bone should be set at the height of the phalanges and in the middle of the geometry.

.Full_Toes_Right bone
[%header, cols="20, 80"]
|===

2+^| Full_Toes_Right 

| *Axis*
| Direction

| *X*
| Up

| *Y*
| Forward

| *Z*
| Side
|===


//Note: Please add a figure and description.
//[Image Placeholder]
