= General

A human is a bipedal being that can be represented by an object in 3D geometry.

The human 3D geometry is generically structured into the node structure and skeleton (also often called armature) defined in the <<Structure overview>>. The structure starts with a Root node as a parent group for all other nodes in the structure. Splitting the object into different parts, such as clothing, hair, and accessories, enables the animation and exchange of parts. Not all nodes have to be present in every human 3D model. Custom object parts may be added to facilitate and better visualize additional use cases, but all custom parts shall adhere to the specified structure principle.

In the coordinate system for human 3D geometry, the x-axis points forwards, the y-axis points sidewards, and the z-axis points upwards. The default pose is the A-pose. The naming convention makes it possible to mirror one side of the skeleton to the other. The bone orientation allows (future) animations to be mirrored an both sides.