= General

A human is any object, which represents a human character.

The human 3D geometry is generically structured into the node structure and skeleton (also often called armature) defined in the next section. The structure starts with a Root node as a parent group for all other nodes in the structure.  A separation of object parts into different groups enables animation and exchange of parts, such clothing, hair and accessories. Each node is an empty node representing the coordinate origin of the contained geometry. Meshes are to be placed in the corresponding group node. Not all nodes have to be present in every human 3D model. Additional group nodes may be added to facilitate additional use-cases, but they shall follow the same principle.

The human 3D geometry is orientated at X as Forward-Axis, Y as Side-Axis and Z as Up-Axis and the default pose is the A-pose. The naming conventions allows to mirror one side of the skeleton to the other. The bone orientation allows (future) animations to be mirrored an both sides.

