= Notes from Miro board


* *Static Equipment* like bicycles, strollers, suitcase, dog (things that can be picked up and released) should be separate assets. thus equipment_static should be removed from the hierarchy  
* *Hip*: Bone coordinate frame axis have to be specified  
* *Neck*: For Facial Animation, more bones (Articulated_Face) may be added on top of Neck and Head
* *Head*: For Facial Animation, more bones (Articulated_Face) may be added on top of Neck and Head. Some use cases (like in-cabin eye-tracking) require eyes. Eyes and facial movement may use an extensions to the rig.
* *Full Hand Right*: Motorcycle Rider/Cyclist/Scooter Rider/ Person carrying stuff needs fingers. For Hand Animation, additional bones (Articulated_Hand) may be added in Parallel to Full_Hand.
* *Full Hand Left*: Motorcycle Rider/Cyclist/Scooter Rider/ Person carrying stuff needs fingers. For Hand Animation, additional bones (Articulated_Hand) may be added in Parallel to Full_Hand. Help bones (e.g. center of a closed hand) could be helpful.  
* *Full Foot Right*: For Foot Animation, additional bones (Articulated_Foot) may be added in Parallel to Full_Foot. Barefoot Pedestrians would need articulated toes.  
* *Full Foot Left*: For Foot Animation, additional bones (Articulated_Foot) may be added in Parallel to Full_Foot. Barefoot Pedestrians would need articulated toes.  
* *Grp_Equipment_Dynamic*: If equipment is very specific for a human asset, rather small, not self-contained or animated, it can be part of the human asset.



*The following adjustments have been made to the example model according to the Miroboard:*

* The second detailed LOD level was set as the default, but simplified
* added bones for foot and toe
* added bones for hand and thumb
* added bones for hip => Removed, since OSI only supports one hip, lower and upper spine
* added bones for eyes
* added groups for accessories, clothing, hair, body => removed and replaced with prefixes of the mesh names
* Added hip bones as seperate bone to stay compatible between (future) LOD levels. Therefore the bones can all have an unique name 
and can be used for the (future) animations as before => Removed, since OSI only supports one hip, lower and upper spine
* renamed some bones
* adjusted axis orientation
* adjusted bone orientation, so mirroring would be possible to use for animating the character

Full_Hand <- Hand -> Hannd (with Upper_Finger and Lower_Finger)
Full_Foot <- Foot -> Foot (with Upper_Toe and Lower_Toe)



