= File format

ifndef::include-only-once[]
:root-path: ../
:imagesdir: {root-path}/_images
:includedir: {root-path}/_images
include::{root-path}_config.adoc[]
endif::[]

ASAM OpenMATERIAL does not define its own 3D model format.
The geometry specification however defines coordinate systems, units, node hierarchies, and more, which can be applied in different 3D model formats.

ASAM OpenMATERIAL supports the 3D model file formats glTF, FBX and USD with the following considerations.

**glTF**

ASAM OpenMATERIAL 3D models in glTF format SHALL conform to the official https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html[glTF specification].

The glTF coordinate system is defined as a right-handed system with +Y as up, +Z as forward, and -X as right. The front of a glTF asset faces +Z.
This differs from how coordinate systems are defined in OpenMATERIAL, see xref:general.adoc[].
While modeling, the OpenMATERIAL coordinate definitions SHALL be used.
During export to glTF and import from glTF, a coordinate transformation SHALL be applied to conform to the glTF specification.
Common modeling tools, e.g. Blender, do this automatically.

**FBX**

FBX does not have a formal specification, but ASAM OpenMATERIAL 3D models in FBX format SHALL be compatible with the official https://help.autodesk.com/view/FBX/2020/ENU/?guid=FBX_Developer_Help_welcome_to_the_fbx_sdk_html[AUTODESK FBX SDK].

**USD**

ASAM OpenMATERIAL 3D models in USD format SHALL conform to the official https://openusd.org/release/index.html[USD specification].

The USD coordinate specification allows either +Y as up or +Z as up, defined in an upAxis metadatum.
To follow the OpenMATERIAL geometry specification, +Z SHALL be used as the up axis.
