= General structure

== Dimensions
The unit used for object dimensions is meters.

== Coordinate systems
The local coordinate system is a right-handed coordinate system according to ISO 8855 with the axes pointing to the directions as follows. For a non-rotated coordinate system, the following applies:

* Forward matches x-axis
* Left matches y-axis
* Up matches z-axis

The coordinate system is in line with ASAM OpenDRIVE, ASAM OpenSCENARIO, and ASAM OSI.

////
Origins of the coordinate frames for specific object classes are under
discussion.
////

== Naming conventions
The following naming conventions apply to material files:

* Use prefixes in the 3D model file name to show that it is up to standard
** Example: `omg_` (open material geometry)
* Same file name for 3D model and asset file
** Example of 3D model file: `omg_my-model.gltf`
** Example of asset file: `omg_my-model.x...` (extension see below)

////
Putting more information in file name to be discussed for specific object classes.
////

== Asset file (mapping, metadata,...)
* json format
* File extension (different from material files)
** xoma (open material asset)
** xomg (open material geometry)
* Contents
** Metadata
** Material mapping (with possibility to easily change assignment)
** Optional link to another asset file to facilitate instancing (same asset file for different 3D models)
** Semantic information (labels) for sub-meshes ?
** Description of coordinates, pivot points and so on instead of hierarchy in 3D model file ?
** Assigning data streams (for example, wheel rotation) to certain sub-meshes ?

== Requirements (quality, semantic/animation/material structure, and so on)
* Separation of materials
* ...

== Recommendations (performance measures and so on)
* Same texel density within a file
* Object class dependent recommendations for mesh resolution
* Performance recommendations ? (for example, use alpha textures for vegetation)
* ...
