= Metadata

* (Stored in asset file)
* (Independent of 3D file format)

//-

* 3D Model name/title, unique ID, version
* OpenMATERIAL version
* Author and authoring tool, creation date
* Origin/source (3D scan, modeled by image, public ressource, ...)
* Description field (free text)
* Copyright information (notice/protection) and license type (CC0, GPL, ...)
* Labeling (object class, materials, abstraction level: Scene/object/component/animation)
* Complexity information (Mesh/texture resolution or class (real-time, non-real-time), ...)
* Used technologies (alpha textures, normal maps (DirectX or OpenGL), and so on) ?
* Validation information
* Material mapping type (per mesh, per vertex, per texel)
* Class-dependent metadata ?
** Vehicles:
*** Axes and wheel positions

////
What about other geometrical data in the Asset file? E.g. Thickness of meshes, mass of meshes etc. (CL)  

Within the metadata, the available nodes of a model should be spcified. I can image classes of model fidelity specifying sets of nodes (LF)  

Eyepoint limits could be part of the metadata (LF)  
////
